//! Per-transaction / per-graph PROV-O (6.2): every commit generates its graphs
//! as PROV entities, `GET /api/datasets/:id/provenance` assembles a dataset's
//! trail as plain PROV-O, and the DCAT catalogue attributes the dataset and
//! names the activity that last changed it (it declared the prov prefix and
//! emitted no PROV triple).

mod common;

use axum::body::Body;
use axum::http::{header, Method, Request, StatusCode};
use axum::Router;
use common::*;
use oxigraph::sparql::QueryResults;
use serde_json::json;
use tower::ServiceExt as _;

const G: &str = "urn:prov:g1";

async fn text(
    app: &Router,
    method: Method,
    uri: &str,
    token: Option<&str>,
    ct: Option<&str>,
    body: &str,
) -> (StatusCode, String) {
    let mut b = Request::builder().method(method).uri(uri);
    if let Some(t) = token {
        b = b.header(header::AUTHORIZATION, format!("Bearer {t}"));
    }
    if let Some(c) = ct {
        b = b.header(header::CONTENT_TYPE, c);
    }
    let resp = app
        .clone()
        .oneshot(b.body(Body::from(body.to_string())).unwrap())
        .await
        .unwrap();
    let st = resp.status();
    (st, body_text(resp.into_body()).await)
}

#[tokio::test]
async fn commits_generate_graph_entities_and_the_dataset_has_a_prov_trail() {
    let (state, token) = admin_state();
    let app = test_app(state.clone());
    let (st, txt) = text(
        &app,
        Method::POST,
        "/api/datasets",
        Some(&token),
        Some("application/json"),
        &json!({ "name": "provd", "owner_type": "user", "owner_id": "adm", "visibility": "public" }).to_string(),
    )
    .await;
    assert!(st.is_success(), "{txt}");
    let ds: serde_json::Value = serde_json::from_str(&txt).unwrap();
    let id = ds["id"].as_str().unwrap().to_string();
    text(
        &app,
        Method::POST,
        &format!("/api/datasets/{id}/graphs"),
        Some(&token),
        Some("application/json"),
        &json!({ "graph_iri": G }).to_string(),
    )
    .await;
    let (st, _) = text(
        &app,
        Method::PUT,
        &format!("/store?graph={}", url_encode(G)),
        Some(&token),
        Some("text/turtle"),
        "<urn:p:a> <urn:p:p> \"1\" .",
    )
    .await;
    assert!(st.is_success());

    // 1. The commit graph carries PROV links from the graph's side.
    let ask = |q: &str| match state.store.query(q) {
        Ok(QueryResults::Boolean(b)) => b,
        other => panic!("ASK failed: {:?}", other.err().map(|e| e.to_string())),
    };
    let dump = || {
        String::from_utf8(
            state
                .store
                .graph_store_get(
                    Some("urn:system:commit-log"),
                    oxigraph::io::RdfFormat::NTriples,
                )
                .unwrap(),
        )
        .unwrap()
    };
    assert!(
        ask(&format!("ASK {{ GRAPH <urn:system:commit-log> {{ <{G}> a <http://www.w3.org/ns/prov#Entity> ; <http://www.w3.org/ns/prov#wasGeneratedBy> ?c . ?c a <http://www.w3.org/ns/prov#Activity> ; <http://www.w3.org/ns/prov#wasAssociatedWith> ?agent . ?agent a <http://www.w3.org/ns/prov#Agent> }} }}")),
        "the written graph is a prov:Entity generated by the commit's activity, whose agent is typed:\n{}",
        dump()
    );
    assert!(
        ask("ASK { GRAPH <urn:system:commit-log> { ?c <http://www.w3.org/ns/prov#startedAtTime> ?t ; <http://www.w3.org/ns/prov#endedAtTime> ?t } }"),
        "the activity has its interval"
    );

    // 2. The dataset's PROV-O document.
    let (st, ttl) = text(
        &app,
        Method::GET,
        &format!("/api/datasets/{id}/provenance"),
        Some(&token),
        None,
        "",
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{ttl}");
    for needle in [
        "a prov:Entity, dcat:Dataset",
        "prov:wasAttributedTo <http://localhost:7878/user/adm>",
        "a prov:Activity",
        "prov:wasAssociatedWith <http://localhost:7878/users/adm>",
        &format!("prov:generated <{G}>"),
        &format!("<{G}> a prov:Entity"),
        "Graph Store PUT",
    ] {
        assert!(ttl.contains(needle), "provenance lacks `{needle}`:\n{ttl}");
    }
    // It parses as Turtle.
    let tmp = open_triplestore::store::TripleStore::in_memory().unwrap();
    tmp.load_str(&ttl, oxigraph::io::RdfFormat::Turtle, Some("urn:check"))
        .expect("valid Turtle");

    // 3. A version shows up as a revision chain.
    text(
        &app,
        Method::POST,
        &format!("/api/datasets/{id}/versions"),
        Some(&token),
        Some("application/json"),
        &json!({ "version": "1.0.0" }).to_string(),
    )
    .await;
    let (_, ttl) = text(
        &app,
        Method::GET,
        &format!("/api/datasets/{id}/provenance"),
        Some(&token),
        None,
        "",
    )
    .await;
    assert!(
        ttl.contains(&format!("/dataset/{id}/version/1.0.0> a prov:Entity")),
        "{ttl}"
    );
    assert!(
        ttl.contains("Cut version 1.0.0"),
        "the version commit is an activity in the trail"
    );

    // 4. DCAT attributes the dataset and names its last activity.
    let (st, void) = text(&app, Method::GET, "/.well-known/void", None, None, "").await;
    assert_eq!(st, StatusCode::OK);
    // The dataset's own block starts with its IRI on a line of its own; the
    // catalogue's `dcat:dataset <…>` reference comes first and must be skipped.
    let block = void
        .split(&format!("<http://localhost:7878/dataset/{id}>\n"))
        .nth(1)
        .expect("dataset block in catalogue");
    let block = &block[..block.find(" .\n").unwrap_or(block.len())];
    assert!(
        block.contains("prov:wasAttributedTo <http://localhost:7878/user/adm>"),
        "{block}"
    );
    assert!(
        block.contains("prov:wasGeneratedBy <http://localhost:7878/commit/"),
        "{block}"
    );

    // 5. A stranger cannot read a private dataset's trail.
    let (st, _) = text(
        &app,
        Method::PUT,
        &format!("/api/datasets/{id}"),
        Some(&token),
        Some("application/json"),
        &json!({ "name": "provd", "visibility": "private" }).to_string(),
    )
    .await;
    assert!(st.is_success());
    let (st, _) = text(
        &app,
        Method::GET,
        &format!("/api/datasets/{id}/provenance"),
        None,
        None,
        "",
    )
    .await;
    assert_eq!(st, StatusCode::NOT_FOUND);
}
