PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX country: <http://downlode.org/rdf/iso-3166/countries#>
# Property path: one-or-more joined with data, products per top-level type
SELECT ?top (COUNT(DISTINCT ?product) AS ?n) WHERE { ?top rdfs:subClassOf inst:ProductType1 . ?leaf rdfs:subClassOf+ ?top . ?product a ?leaf } GROUP BY ?top
