//! Per-schema IFC tables: every entity of IFC2X3, IFC4 and IFC4X3_ADD2 with
//! its supertype, its explicit attributes (in STEP order, with optionality and
//! declared type) and the names of its derived and inverse attributes; every
//! defined type, enumeration and select; the data types an IDS `dataType` may
//! name; and the IFC2X3 occurrence/type mapping table of the IDS implementer
//! documentation.
//!
//! The tables are generated by `scripts/gen_ifc_schema_tables.py` from the
//! pinned EXPRESS schemas and IDS documents (see that script and NOTICE), and
//! parsed once, lazily, from the embedded text.

// A table module: the server binary compiles every module but reaches only
// part of this API (the IDS importer); the library exports all of it.
#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

/// The three schemas IDS 1.0 knows (`ifcVersion`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SchemaId {
    Ifc2x3,
    Ifc4,
    Ifc4x3,
}

impl SchemaId {
    pub const ALL: [SchemaId; 3] = [SchemaId::Ifc2x3, SchemaId::Ifc4, SchemaId::Ifc4x3];

    /// The schema of a STEP file's `FILE_SCHEMA`: `IFC2X3`, `IFC4` (any
    /// addendum) or `IFC4X3…` (4.3 and its addenda).
    pub fn from_file_schema(s: &str) -> Option<SchemaId> {
        let s = s.trim().to_ascii_uppercase();
        if s.starts_with("IFC2X3") {
            Some(SchemaId::Ifc2x3)
        } else if s.starts_with("IFC4X3") {
            Some(SchemaId::Ifc4x3)
        } else if s.starts_with("IFC4") {
            Some(SchemaId::Ifc4)
        } else {
            None
        }
    }

    /// An IDS `ifcVersion` token (exact, as the XSD enumerates them).
    pub fn from_ids(s: &str) -> Option<SchemaId> {
        match s {
            "IFC2X3" => Some(SchemaId::Ifc2x3),
            "IFC4" => Some(SchemaId::Ifc4),
            "IFC4X3_ADD2" => Some(SchemaId::Ifc4x3),
            _ => None,
        }
    }

    /// The IDS `ifcVersion` token.
    pub fn ids_name(self) -> &'static str {
        match self {
            SchemaId::Ifc2x3 => "IFC2X3",
            SchemaId::Ifc4 => "IFC4",
            SchemaId::Ifc4x3 => "IFC4X3_ADD2",
        }
    }

    pub fn schema(self) -> &'static Schema {
        static S: [OnceLock<Schema>; 3] = [OnceLock::new(), OnceLock::new(), OnceLock::new()];
        let (slot, text) = match self {
            SchemaId::Ifc2x3 => (&S[0], include_str!("schema/IFC2X3.txt")),
            SchemaId::Ifc4 => (&S[1], include_str!("schema/IFC4.txt")),
            SchemaId::Ifc4x3 => (&S[2], include_str!("schema/IFC4X3_ADD2.txt")),
        };
        slot.get_or_init(|| Schema::parse(self, text))
    }
}

/// An EXPRESS simple type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Primitive {
    String,
    Real,
    Integer,
    Number,
    Boolean,
    Logical,
    Binary,
}

impl Primitive {
    fn parse(s: &str) -> Option<Primitive> {
        Some(match s {
            "STRING" => Primitive::String,
            "REAL" => Primitive::Real,
            "INTEGER" => Primitive::Integer,
            "NUMBER" => Primitive::Number,
            "BOOLEAN" => Primitive::Boolean,
            "LOGICAL" => Primitive::Logical,
            "BINARY" => Primitive::Binary,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone)]
pub enum TypeDef {
    Simple(Primitive),
    /// A defined type over another named type (`IfcBoxAlignment = IfcLabel`).
    Alias(String),
    Enum(Vec<String>),
    Select(Vec<String>),
    /// A defined aggregate (`IfcCompoundPlaneAngleMeasure = LIST OF INTEGER`).
    Aggregate(String),
}

#[derive(Debug, Clone)]
pub struct Attr {
    pub name: String,
    pub optional: bool,
    /// Declared type: a type or entity name, an EXPRESS primitive, or
    /// `AGG:<element>` for a LIST/SET/ARRAY/BAG.
    pub ty: String,
}

#[derive(Debug, Clone)]
pub struct Entity {
    /// CamelCase, as the schema writes it.
    pub name: String,
    /// Upper-case supertype, `None` for a root.
    pub supertype: Option<String>,
    pub is_abstract: bool,
    /// Explicit attributes this entity adds, in order.
    pub own_attrs: Vec<Attr>,
    /// Attributes derived here (DERIVE, including inherited explicit
    /// attributes redeclared as derived).
    pub derived: Vec<String>,
    pub inverse: Vec<String>,
}

/// How an attribute's declared type resolves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttrKind {
    Entity,
    Select,
    Enum,
    Aggregate,
    Primitive(Primitive),
    Unknown,
}

pub struct Schema {
    pub id: SchemaId,
    entities: HashMap<String, Entity>,
    types: HashMap<String, TypeDef>,
    /// Upper-case type name → CamelCase.
    type_names: HashMap<String, String>,
}

impl Schema {
    fn parse(id: SchemaId, text: &str) -> Schema {
        let mut entities: HashMap<String, Entity> = HashMap::new();
        let mut types = HashMap::new();
        let mut type_names = HashMap::new();
        let mut current: Option<String> = None;
        for line in text.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let cols: Vec<&str> = line.split('\t').collect();
            match cols[0] {
                "T" => {
                    let name = cols[1];
                    let detail = cols.get(3).copied().unwrap_or("");
                    let words = || {
                        detail
                            .split(' ')
                            .filter(|w| !w.is_empty())
                            .map(str::to_string)
                            .collect()
                    };
                    let def = match cols[2] {
                        "simple" => {
                            TypeDef::Simple(Primitive::parse(detail).unwrap_or(Primitive::String))
                        }
                        "alias" => TypeDef::Alias(detail.to_ascii_uppercase()),
                        "enum" => TypeDef::Enum(words()),
                        "select" => TypeDef::Select(
                            detail
                                .split(' ')
                                .filter(|w| !w.is_empty())
                                .map(|w| w.to_ascii_uppercase())
                                .collect(),
                        ),
                        _ => TypeDef::Aggregate(detail.to_ascii_uppercase()),
                    };
                    let upper = name.to_ascii_uppercase();
                    type_names.insert(upper.clone(), name.to_string());
                    types.insert(upper, def);
                }
                "E" => {
                    let upper = cols[1].to_ascii_uppercase();
                    entities.insert(
                        upper.clone(),
                        Entity {
                            name: cols[1].to_string(),
                            supertype: (cols[2] != "-").then(|| cols[2].to_ascii_uppercase()),
                            is_abstract: cols.get(3) == Some(&"1"),
                            own_attrs: Vec::new(),
                            derived: Vec::new(),
                            inverse: Vec::new(),
                        },
                    );
                    current = Some(upper);
                }
                "A" | "D" | "I" => {
                    let Some(e) = current.as_ref().and_then(|c| entities.get_mut(c)) else {
                        continue;
                    };
                    match cols[0] {
                        "A" => e.own_attrs.push(Attr {
                            name: cols[1].to_string(),
                            optional: cols.get(2) == Some(&"1"),
                            ty: cols.get(3).copied().unwrap_or("").to_string(),
                        }),
                        "D" => e.derived.push(cols[1].to_string()),
                        _ => e.inverse.push(cols[1].to_string()),
                    }
                }
                _ => {}
            }
        }
        Schema {
            id,
            entities,
            types,
            type_names,
        }
    }

    pub fn entity(&self, upper: &str) -> Option<&Entity> {
        self.entities.get(upper)
    }

    pub fn has_entity(&self, upper: &str) -> bool {
        self.entities.contains_key(upper)
    }

    /// Upper-case names of every entity.
    pub fn entity_names(&self) -> impl Iterator<Item = &str> {
        self.entities.keys().map(String::as_str)
    }

    /// The entity and its ancestors, the entity first.
    pub fn lineage<'a>(&'a self, upper: &str) -> Vec<&'a Entity> {
        let mut out = Vec::new();
        let mut cur = self.entities.get(upper);
        while let Some(e) = cur {
            out.push(e);
            if out.len() > 64 {
                break;
            }
            cur = e.supertype.as_deref().and_then(|s| self.entities.get(s));
        }
        out
    }

    /// `upper` is `ancestor` or one of its subtypes.
    pub fn is_a(&self, upper: &str, ancestor: &str) -> bool {
        self.lineage(upper)
            .iter()
            .any(|e| e.name.eq_ignore_ascii_case(ancestor))
    }

    /// Every explicit attribute of the entity in STEP order (the root's
    /// first), each with whether the entity (or an ancestor below the
    /// declaring one) redeclares it as derived — written `*` in a file.
    pub fn attributes<'a>(&'a self, upper: &str) -> Vec<(&'a Attr, bool)> {
        let lineage = self.lineage(upper);
        let derived: Vec<&str> = lineage
            .iter()
            .flat_map(|e| e.derived.iter().map(String::as_str))
            .collect();
        lineage
            .iter()
            .rev()
            .flat_map(|e| e.own_attrs.iter())
            .map(|a| (a, derived.contains(&a.name.as_str())))
            .collect()
    }

    /// Names of the entity's derived attributes (own and inherited).
    pub fn derived_attributes(&self, upper: &str) -> Vec<&str> {
        self.lineage(upper)
            .iter()
            .flat_map(|e| e.derived.iter().map(String::as_str))
            .collect()
    }

    /// Names of the entity's inverse attributes (own and inherited).
    pub fn inverse_attributes(&self, upper: &str) -> Vec<&str> {
        self.lineage(upper)
            .iter()
            .flat_map(|e| e.inverse.iter().map(String::as_str))
            .collect()
    }

    pub fn type_def(&self, upper: &str) -> Option<&TypeDef> {
        self.types.get(upper)
    }

    /// CamelCase of a type or entity name.
    pub fn camel<'a>(&'a self, upper: &str) -> Option<&'a str> {
        self.type_names
            .get(upper)
            .map(String::as_str)
            .or_else(|| self.entities.get(upper).map(|e| e.name.as_str()))
    }

    /// How a declared attribute type resolves (aliases followed).
    pub fn attr_kind(&self, ty: &str) -> AttrKind {
        if ty.starts_with("AGG:") {
            return AttrKind::Aggregate;
        }
        if let Some(p) = Primitive::parse(ty) {
            return AttrKind::Primitive(p);
        }
        let mut cur = ty.to_ascii_uppercase();
        for _ in 0..16 {
            if self.entities.contains_key(&cur) {
                return AttrKind::Entity;
            }
            match self.types.get(&cur) {
                Some(TypeDef::Simple(p)) => return AttrKind::Primitive(*p),
                Some(TypeDef::Alias(next)) => cur = next.clone(),
                Some(TypeDef::Enum(_)) => return AttrKind::Enum,
                Some(TypeDef::Select(_)) => return AttrKind::Select,
                Some(TypeDef::Aggregate(_)) => return AttrKind::Aggregate,
                None => return AttrKind::Unknown,
            }
        }
        AttrKind::Unknown
    }

    /// The primitive under a defined type, when it has one.
    pub fn primitive_of(&self, type_upper: &str) -> Option<Primitive> {
        match self.attr_kind(type_upper) {
            AttrKind::Primitive(p) => Some(p),
            _ => None,
        }
    }

    /// Values of an enumeration type.
    pub fn enum_values(&self, type_upper: &str) -> Option<&[String]> {
        match self.types.get(type_upper) {
            Some(TypeDef::Enum(v)) => Some(v),
            _ => None,
        }
    }

    /// The entity's `PredefinedType` attribute, when it has one, and its
    /// enumeration.
    pub fn predefined_type_attr(&self, upper: &str) -> Option<(usize, &Attr)> {
        self.attributes(upper)
            .into_iter()
            .enumerate()
            .find(|(_, (a, _))| a.name == "PredefinedType")
            .map(|(i, (a, _))| (i, a))
    }

    /// Position of a named explicit attribute in the entity's STEP record.
    pub fn attr_index(&self, upper: &str, name: &str) -> Option<usize> {
        self.attributes(upper)
            .iter()
            .position(|(a, _)| a.name == name)
    }
}

/// XSD base type of an IDS value restriction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XsBase {
    String,
    Double,
    Integer,
    Boolean,
    Date,
    DateTime,
    Time,
    Duration,
}

impl XsBase {
    pub fn parse(s: &str) -> Option<XsBase> {
        Some(match s {
            "xs:string" => XsBase::String,
            "xs:double" => XsBase::Double,
            "xs:integer" => XsBase::Integer,
            "xs:boolean" => XsBase::Boolean,
            "xs:date" => XsBase::Date,
            "xs:dateTime" => XsBase::DateTime,
            "xs:time" => XsBase::Time,
            "xs:duration" => XsBase::Duration,
            _ => return None,
        })
    }

    pub fn as_str(self) -> &'static str {
        match self {
            XsBase::String => "xs:string",
            XsBase::Double => "xs:double",
            XsBase::Integer => "xs:integer",
            XsBase::Boolean => "xs:boolean",
            XsBase::Date => "xs:date",
            XsBase::DateTime => "xs:dateTime",
            XsBase::Time => "xs:time",
            XsBase::Duration => "xs:duration",
        }
    }

    /// The lexical rule the IDS documentation gives for a value of this base.
    pub fn lexically_valid(self, v: &str) -> bool {
        let digits = |s: &str| !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit());
        match self {
            XsBase::String => true,
            XsBase::Boolean => matches!(v, "true" | "false" | "0" | "1"),
            XsBase::Integer => {
                let s = v.strip_prefix(['+', '-']).unwrap_or(v);
                digits(s)
            }
            XsBase::Double => {
                if matches!(v, "NaN" | "+INF" | "-INF") {
                    return true;
                }
                let s = v.strip_prefix(['+', '-']).unwrap_or(v);
                let (mantissa, exp) = match s.find(['e', 'E']) {
                    Some(i) => (&s[..i], Some(&s[i + 1..])),
                    None => (s, None),
                };
                if let Some(e) = exp {
                    if !digits(e.strip_prefix(['+', '-']).unwrap_or(e)) {
                        return false;
                    }
                }
                let (int, frac) = match mantissa.split_once('.') {
                    Some((i, f)) => (i, f),
                    None => (mantissa, ""),
                };
                (int.is_empty() || digits(int))
                    && (frac.is_empty() || digits(frac))
                    && !(int.is_empty() && frac.is_empty())
            }
            XsBase::Date => {
                let b = v.as_bytes();
                b.len() >= 10
                    && digits(&v[0..4])
                    && b[4] == b'-'
                    && digits(&v[5..7])
                    && b[7] == b'-'
                    && digits(&v[8..10])
                    && tz_ok(&v[10..])
            }
            XsBase::Time => time_ok(v),
            XsBase::DateTime => match v.split_once('T') {
                Some((d, t)) => XsBase::Date.lexically_valid(d) && time_ok(t),
                None => false,
            },
            XsBase::Duration => {
                let s = v.strip_prefix(['+', '-']).unwrap_or(v);
                let Some(rest) = s.strip_prefix('P') else {
                    return false;
                };
                let (date, time) = match rest.split_once('T') {
                    Some((d, t)) => (d, Some(t)),
                    None => (rest, None),
                };
                let part_ok = |s: &str, units: &[u8]| {
                    let mut i = 0usize;
                    let b = s.as_bytes();
                    let mut last = 0usize;
                    while i < b.len() {
                        let start = i;
                        while i < b.len() && b[i].is_ascii_digit() {
                            i += 1;
                        }
                        if i == start || i >= b.len() {
                            return false;
                        }
                        let Some(pos) = units.iter().position(|u| *u == b[i]) else {
                            return false;
                        };
                        if pos < last {
                            return false;
                        }
                        last = pos + 1;
                        i += 1;
                    }
                    true
                };
                part_ok(date, b"YMD") && time.is_none_or(|t| part_ok(t, b"HMS"))
            }
        }
    }
}

fn tz_ok(s: &str) -> bool {
    let b = s.as_bytes();
    s.is_empty()
        || s == "Z"
        || (b.len() == 6
            && (b[0] == b'+' || b[0] == b'-')
            && b[1..3].iter().all(u8::is_ascii_digit)
            && b[3] == b':'
            && b[4..6].iter().all(u8::is_ascii_digit))
}

fn time_ok(v: &str) -> bool {
    let b = v.as_bytes();
    if b.len() < 8
        || !b[0..2].iter().all(u8::is_ascii_digit)
        || b[2] != b':'
        || !b[3..5].iter().all(u8::is_ascii_digit)
        || b[5] != b':'
        || !b[6..8].iter().all(u8::is_ascii_digit)
    {
        return false;
    }
    let mut rest = &v[8..];
    if let Some(frac) = rest.strip_prefix('.') {
        let n = frac.bytes().take_while(u8::is_ascii_digit).count();
        if n == 0 {
            return false;
        }
        rest = &frac[n..];
    }
    tz_ok(rest)
}

/// One row of the IDS data-type table.
#[derive(Debug, Clone)]
pub struct IdsDataType {
    pub schemas: Vec<SchemaId>,
    /// `None` for types no restriction may constrain (IFCBINARY).
    pub base: Option<XsBase>,
}

/// The data types an IDS property `dataType` may name (upper case).
pub fn ids_datatype(upper: &str) -> Option<&'static IdsDataType> {
    static T: OnceLock<HashMap<String, IdsDataType>> = OnceLock::new();
    T.get_or_init(|| {
        include_str!("schema/ids_datatypes.txt")
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .filter_map(|l| {
                let c: Vec<&str> = l.split('\t').collect();
                Some((
                    c.first()?.to_string(),
                    IdsDataType {
                        schemas: c
                            .get(1)?
                            .split(',')
                            .filter_map(SchemaId::from_ids)
                            .collect(),
                        base: c.get(2).and_then(|b| XsBase::parse(b)),
                    },
                ))
            })
            .collect()
    })
    .get(upper)
}

/// The IFC unit type (`LENGTHUNIT`, `MASSDENSITYUNIT`, …) a measure IDS
/// compares in SI units is converted from, for the measures the IDS units
/// table lists (upper-case measure name).
pub fn ids_unit_type(measure_upper: &str) -> Option<&'static str> {
    static T: OnceLock<HashMap<String, String>> = OnceLock::new();
    T.get_or_init(|| {
        include_str!("schema/ids_units.txt")
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .filter_map(|l| {
                let mut c = l.split('\t');
                Some((c.next()?.to_string(), c.next()?.to_string()))
            })
            .collect()
    })
    .get(measure_upper)
    .map(String::as_str)
}

/// The IFC2X3 occurrence/type mapping: (IDS entity name, IFC2X3 occurrence
/// entity, IFC2X3 type entity), all upper case.
pub fn ifc2x3_type_map() -> &'static [(String, String, String)] {
    static T: OnceLock<Vec<(String, String, String)>> = OnceLock::new();
    T.get_or_init(|| {
        include_str!("schema/ifc2x3_type_map.txt")
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .filter_map(|l| {
                let mut c = l.split('\t').map(str::to_ascii_uppercase);
                Some((c.next()?, c.next()?, c.next()?))
            })
            .collect()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_load_with_inherited_attributes_in_step_order() {
        let s = SchemaId::Ifc4.schema();
        let attrs: Vec<&str> = s
            .attributes("IFCWALL")
            .iter()
            .map(|(a, _)| a.name.as_str())
            .collect();
        assert_eq!(
            attrs,
            [
                "GlobalId",
                "OwnerHistory",
                "Name",
                "Description",
                "ObjectType",
                "ObjectPlacement",
                "Representation",
                "Tag",
                "PredefinedType"
            ]
        );
        assert!(s.is_a("IFCWALLSTANDARDCASE", "IfcWall"));
        assert!(!s.is_a("IFCWALL", "IfcWallStandardCase"));
        // IFC2X3's IfcWall has no PredefinedType.
        assert!(SchemaId::Ifc2x3
            .schema()
            .predefined_type_attr("IFCWALL")
            .is_none());
        assert!(s.derived_attributes("IFCCARTESIANPOINT").contains(&"Dim"));
        assert!(s.inverse_attributes("IFCPERSON").contains(&"EngagedIn"));
        // IfcSIUnit redeclares the inherited Dimensions as derived (`*`).
        assert!(s
            .attributes("IFCSIUNIT")
            .iter()
            .any(|(a, d)| a.name == "Dimensions" && *d));
        assert_eq!(
            s.attr_kind("IfcLabel"),
            AttrKind::Primitive(Primitive::String)
        );
        assert_eq!(
            s.attr_kind("IfcBoxAlignment"),
            AttrKind::Primitive(Primitive::String)
        );
        assert_eq!(s.attr_kind("IfcValue"), AttrKind::Select);
        assert_eq!(s.attr_kind("IfcWallTypeEnum"), AttrKind::Enum);
        assert_eq!(s.attr_kind("IfcTaskTime"), AttrKind::Entity);
        assert!(SchemaId::Ifc4x3.schema().has_entity("IFCALIGNMENT"));
        assert!(!SchemaId::Ifc4.schema().has_entity("IFCALIGNMENT"));
    }

    #[test]
    fn the_ids_tables_load() {
        let label = ids_datatype("IFCLABEL").expect("IFCLABEL");
        assert_eq!(label.base, Some(XsBase::String));
        assert_eq!(label.schemas.len(), 3);
        assert_eq!(
            ids_datatype("IFCLENGTHMEASURE").unwrap().base,
            Some(XsBase::Double)
        );
        assert!(!ids_datatype("IFCDURATION")
            .unwrap()
            .schemas
            .contains(&SchemaId::Ifc2x3));
        assert!(ifc2x3_type_map()
            .iter()
            .any(|(n, o, t)| n == "IFCAIRTERMINAL"
                && o == "IFCFLOWTERMINAL"
                && t == "IFCAIRTERMINALTYPE"));
    }

    #[test]
    fn xsd_lexical_rules_follow_the_ids_table() {
        for ok in [
            "42", "42.", "42.0", ".5", "1.2345e3", "1.2345E3", "-1", "+3.0E-2", "NaN",
        ] {
            assert!(XsBase::Double.lexically_valid(ok), "{ok}");
        }
        for bad in ["42,3", "123,4.5", "", ".", "1e", "abc"] {
            assert!(!XsBase::Double.lexically_valid(bad), "{bad}");
        }
        assert!(XsBase::Integer.lexically_valid("42"));
        for bad in ["42.", "42.0", "42.3", ""] {
            assert!(!XsBase::Integer.lexically_valid(bad), "{bad}");
        }
        assert!(XsBase::Boolean.lexically_valid("false"));
        assert!(!XsBase::Boolean.lexically_valid("FALSE"));
        assert!(XsBase::Date.lexically_valid("2022-01-01"));
        assert!(XsBase::Duration.lexically_valid("PT16H"));
        assert!(!XsBase::Duration.lexically_valid("16H"));
        assert!(XsBase::DateTime.lexically_valid("2022-01-01T10:00:00Z"));
    }
}
