//! CSV source for RML: one logical iteration per row, keyed by column name
//! (RML-IO registry §CSV), read with the CSVW dialect a `csvw:Table` source
//! may declare.

use crate::rml::model::CsvDialect;
use crate::rml::terms::{Iteration, Val};

/// The header and the rows. Every cell is a value, an empty one included:
/// CSV has no NULL of its own (RML-IO), so only `rml:null` / `csvw:null`
/// make one.
pub fn load(text: &str, dialect: &CsvDialect) -> Result<(Vec<String>, Vec<Iteration>), String> {
    let mut builder = csv::ReaderBuilder::new();
    builder
        .has_headers(false)
        .flexible(true)
        .delimiter(dialect.delimiter)
        .quote(dialect.quote)
        .double_quote(dialect.double_quote)
        .comment(dialect.comment);
    if !dialect.double_quote {
        builder.escape(Some(b'\\'));
    }
    if dialect.trim {
        builder.trim(csv::Trim::All);
    }
    let mut rdr = builder.from_reader(text.as_bytes());

    let mut records = rdr.records();
    for _ in 0..dialect.skip_rows {
        match records.next() {
            Some(r) => {
                r.map_err(|e| format!("CSV record error: {e}"))?;
            }
            None => break,
        }
    }
    let mut headers: Vec<String> = Vec::new();
    if dialect.header {
        for _ in 0..dialect.header_rows.max(1) {
            match records.next() {
                // The last header row names the columns (CSVW).
                Some(r) => {
                    let r = r.map_err(|e| format!("CSV header error: {e}"))?;
                    headers = r.iter().map(str::to_string).collect();
                }
                None => break,
            }
        }
    }

    let mut out = Vec::new();
    for (n, result) in records.enumerate() {
        let record = result.map_err(|e| format!("CSV record error: {e}"))?;
        if !dialect.header && headers.len() < record.len() {
            // CSVW names the columns of a header-less table `_col.1`, `_col.2`, …
            headers = (1..=record.len()).map(|i| format!("_col.{i}")).collect();
        }
        if dialect.header && record.len() != headers.len() {
            return Err(format!(
                "CSV row {} has {} cells but the header names {} columns",
                n + 1,
                record.len(),
                headers.len()
            ));
        }
        let mut it = Iteration::default();
        for (i, field) in record.iter().enumerate() {
            if let Some(header) = headers.get(i) {
                it.values.insert(header.clone(), vec![Val::text(field)]);
            }
        }
        out.push(it);
    }
    Ok((headers, out))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rml::terms::Record;

    fn first(it: &Iteration, col: &str) -> Option<String> {
        it.values(col).first().map(str::to_string)
    }

    #[test]
    fn the_default_dialect_is_rfc_4180_with_a_header() {
        let (h, rows) = load("id,name\n1,\"A, B\"\n2,\n", &CsvDialect::default()).unwrap();
        assert_eq!(h, ["id", "name"]);
        assert_eq!(first(&rows[0], "name").as_deref(), Some("A, B"));
        assert_eq!(
            first(&rows[1], "name").as_deref(),
            Some(""),
            "an empty cell is a value"
        );
    }

    #[test]
    fn a_csvw_dialect_is_honoured() {
        let d = CsvDialect {
            delimiter: b';',
            quote: b'\'',
            comment: Some(b'#'),
            skip_rows: 1,
            trim: true,
            ..CsvDialect::default()
        };
        let (h, rows) = load("generated by a tool\nid; name\n# a comment\n1;'x;y'\n", &d).unwrap();
        assert_eq!(h, ["id", "name"]);
        assert_eq!(rows.len(), 1);
        assert_eq!(first(&rows[0], "name").as_deref(), Some("x;y"));
        let tsv = CsvDialect {
            delimiter: b'\t',
            ..CsvDialect::default()
        };
        let (_, rows) = load("a\tb\n1\t2\n", &tsv).unwrap();
        assert_eq!(first(&rows[0], "b").as_deref(), Some("2"));
        let headerless = CsvDialect {
            header: false,
            ..CsvDialect::default()
        };
        let (h, rows) = load("1,Ann\n", &headerless).unwrap();
        assert_eq!(h, ["_col.1", "_col.2"]);
        assert_eq!(first(&rows[0], "_col.2").as_deref(), Some("Ann"));
    }

    #[test]
    fn a_ragged_row_is_an_error() {
        let err = load("a,b\n1,2,3\n", &CsvDialect::default()).unwrap_err();
        assert!(err.contains("3 cells"), "{err}");
    }
}
