#!/usr/bin/env python3
"""Generate the per-schema IFC tables the IDS projection and the IDS importer
read: src/ifc/schema/{IFC2X3,IFC4,IFC4X3_ADD2}.txt, ids_datatypes.txt and
ifc2x3_type_map.txt.

    scripts/gen_ifc_schema_tables.py            # fetch the pinned sources, write the tables
    scripts/gen_ifc_schema_tables.py --check    # exit 1 if a table differs from a fresh run
    scripts/gen_ifc_schema_tables.py --sources DIR   # read the sources from DIR instead

Sources (fetched, never vendored; each pinned by commit and SHA-256):

- IFC2X3 TC1 and IFC4 ADD2 TC1 EXPRESS schemas, buildingSMART's
  IFC4.x-development repository (`reference_schemas/`).
- IFC4X3 ADD2 EXPRESS schema (`SCHEMA IFC4X3_ADD2;`), as redistributed in
  ThatOpen's web-ifc repository (`src/schema-generator/IFC4X3.exp`), because
  buildingSMART's own download site refuses scripted requests.
- The IDS documentation (buildingSMART/IDS, the commit the conformance runner
  pins): DataTypes.md (which IFC defined types an IDS `dataType` may name, per
  schema, and the XSD base type of each), ifc2x3-occurrence-type-mapping-table.md
  and the user manual's units.md (the measures IDS compares in SI units, with
  the IFC unit type each converts from).

What is written is names and structure only — entity and type names, the
order, optionality and declared type of explicit attributes, the names of
derived and inverse attributes, enumeration values and select members — the
facts a schema-aware validator needs, reformatted as line tables. The
schemas and the documentation are © buildingSMART International Limited
(CC BY-ND 4.0 / buildingSMART's copyright notice); see NOTICE.
"""
from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "ifc" / "schema"

BSI_DEV = "https://raw.githubusercontent.com/buildingSMART/IFC4.x-development/9b01a271ad04ad321b800568e4744527960750ac/reference_schemas"
WEB_IFC = "https://raw.githubusercontent.com/ThatOpen/engine_web-ifc/44f01bcacb033dfb7790c3160f214fa4bdf25743/src/schema-generator"
IDS = "https://raw.githubusercontent.com/buildingSMART/IDS/870f9c4e6e8f414e737b4d84ca1aa9b46fc6c8f3/Documentation/ImplementersDocumentation"

SOURCES = {
    "IFC2X3_TC1.exp": (f"{BSI_DEV}/IFC2X3_TC1.exp", "e18a1b2c3e29f5256904c83378ccad0850f52287a8d0122d149aba4a417fe5e5"),
    "IFC4_ADD2_TC1.exp": (f"{BSI_DEV}/IFC4_ADD2_TC1.exp", "a2704ba20a1b3d0b7d9b61d6fd37d0baa3b4996ba3e90d968a1d2ca2819d1046"),
    "IFC4X3.exp": (f"{WEB_IFC}/IFC4X3.exp", "f67c8762b13a099c28082061e6f16b9ef1284ceec34069792afc702725675860"),
    "DataTypes.md": (f"{IDS}/DataTypes.md", "5201f8aeb3650f439bc9c09cb8543f553b9b8e779a773f605a05515ef07ff996"),
    "ifc2x3-occurrence-type-mapping-table.md": (
        f"{IDS}/ifc2x3-occurrence-type-mapping-table.md",
        "89f6bf9abb377a436a42016468b873366f516110b19d5900bc071da5a5860af7",
    ),
    "units.md": (
        IDS.replace("ImplementersDocumentation", "UserManual") + "/units.md",
        "00f849957ccc5810f35b54c0ab3367c21aefe59af814c86dcdd7036adf2105ed",
    ),
}

SCHEMAS = [("IFC2X3", "IFC2X3_TC1.exp"), ("IFC4", "IFC4_ADD2_TC1.exp"), ("IFC4X3_ADD2", "IFC4X3.exp")]

HEADER = """# Generated by scripts/gen_ifc_schema_tables.py — edit the generator, not this file.
# Source: {source}
# Names and structure from the IFC schema, © 1996-2026 buildingSMART International
# Limited, used under its copyright notice / CC BY-ND 4.0
# (http://creativecommons.org/licenses/by-nd/4.0/); see NOTICE. Industry Foundation
# Class(TM) and IFC(TM) are trademarks of buildingSMART International Limited.
"""

PRIMITIVES = {"STRING", "REAL", "INTEGER", "NUMBER", "BOOLEAN", "LOGICAL", "BINARY"}


def fetch(name: str, sources_dir: Path | None) -> str:
    url, want = SOURCES[name]
    if sources_dir is not None:
        data = (sources_dir / name).read_bytes()
    else:
        with urllib.request.urlopen(url, timeout=60) as r:
            data = r.read()
    got = hashlib.sha256(data).hexdigest()
    if got != want:
        raise SystemExit(f"{name}: sha256 {got} does not match the pinned {want}")
    return data.decode("utf-8", errors="replace").replace("\r\n", "\n")


def strip_comments(text: str) -> str:
    return re.sub(r"\(\*.*?\*\)", "", text, flags=re.S)


def split_top(text: str, sep: str = ";") -> list[str]:
    """Split on `sep` outside parentheses and string literals."""
    out, depth, cur, quote = [], 0, [], False
    for ch in text:
        if ch == "'":
            quote = not quote
        if not quote:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            elif ch == sep and depth == 0:
                out.append("".join(cur))
                cur = []
                continue
        cur.append(ch)
    if "".join(cur).strip():
        out.append("".join(cur))
    return out


def norm(s: str) -> str:
    return " ".join(s.split())


def type_ref(spec: str) -> str:
    """An attribute's declared type: a type/entity name, a primitive, or
    `AGG:<element>` for LIST/SET/ARRAY/BAG."""
    spec = norm(spec)
    spec = re.sub(r"^OPTIONAL\s+", "", spec)
    if re.match(r"^(LIST|SET|ARRAY|BAG)\b", spec):
        inner = re.sub(r"^(LIST|SET|ARRAY|BAG)\s*(\[[^\]]*\])?\s*OF\s+", "", spec)
        inner = re.sub(r"^(OPTIONAL|UNIQUE)\s+", "", inner)
        inner = re.sub(r"^(OPTIONAL|UNIQUE)\s+", "", inner)
        return "AGG:" + type_ref(inner).replace("AGG:", "")
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)", spec)
    name = m.group(1) if m else spec
    return name


def parse_schema(text: str):
    text = strip_comments(text)
    types: dict[str, tuple[str, str]] = {}
    entities: dict[str, dict] = {}
    for m in re.finditer(r"\bTYPE\s+(\w+)\s*=\s*(.*?);\s*(?:WHERE.*?)?END_TYPE;", text, flags=re.S):
        name, spec = m.group(1), norm(m.group(2))
        if spec.startswith("ENUMERATION OF"):
            vals = re.findall(r"[A-Za-z0-9_]+", spec[len("ENUMERATION OF"):])
            types[name] = ("enum", " ".join(vals))
        elif spec.startswith("SELECT") or spec.startswith("EXTENSIBLE"):
            members = re.findall(r"[A-Za-z0-9_]+", spec.split("(", 1)[1]) if "(" in spec else []
            types[name] = ("select", " ".join(members))
        elif re.match(r"^(LIST|SET|ARRAY|BAG)\b", spec):
            types[name] = ("aggregate", type_ref(spec).replace("AGG:", ""))
        else:
            base = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)", spec).group(1)
            if base in PRIMITIVES:
                types[name] = ("simple", base)
            else:
                types[name] = ("alias", base)
    for m in re.finditer(r"\bENTITY\s+(\w+)(.*?)END_ENTITY;", text, flags=re.S):
        name, body = m.group(1), m.group(2)
        stmts = split_top(body)
        header = stmts[0] if stmts else ""
        abstract = bool(re.search(r"\bABSTRACT\b", header))
        sup = re.search(r"SUBTYPE\s+OF\s*\(\s*(\w+)\s*\)", header)
        ent = {"super": sup.group(1) if sup else "-", "abstract": abstract, "attrs": [], "derived": [], "inverse": []}
        section = "explicit"
        for raw in stmts[1:]:
            s = raw.strip()
            if not s:
                continue
            # A section keyword opens the statement it precedes.
            while True:
                kw = re.match(r"^(DERIVE|INVERSE|UNIQUE|WHERE)\b\s*", s)
                if not kw:
                    break
                section = kw.group(1).lower()
                s = s[kw.end():]
            if not s or ":" not in s:
                continue
            lhs, rhs = s.split(":", 1)
            lhs = lhs.strip()
            if section == "explicit":
                if lhs.startswith("SELF\\"):
                    continue  # a redeclared inherited attribute takes no new position
                optional = bool(re.match(r"^\s*OPTIONAL\b", rhs))
                for attr in [a.strip() for a in lhs.split(",") if a.strip()]:
                    ent["attrs"].append((attr, optional, type_ref(rhs)))
            elif section == "derive":
                ent["derived"].append(lhs.split(".")[-1].strip())
            elif section == "inverse":
                ent["inverse"].append(lhs.strip())
        entities[name] = ent
    return types, entities


def render_schema(schema: str, source: str, types, entities) -> str:
    lines = [HEADER.format(source=source).rstrip("\n"), f"# Schema {schema}: {len(entities)} entities, {len(types)} types.",
             "# T <name> <simple|alias|enum|select|aggregate> <detail>",
             "# E <name> <supertype|-> <abstract 0|1>; then A <attr> <optional 0|1> <type>, D <derived>, I <inverse>"]
    for name in sorted(types):
        kind, detail = types[name]
        lines.append(f"T\t{name}\t{kind}\t{detail}")
    for name in sorted(entities):
        e = entities[name]
        lines.append(f"E\t{name}\t{e['super']}\t{1 if e['abstract'] else 0}")
        for attr, opt, ty in e["attrs"]:
            lines.append(f"A\t{attr}\t{1 if opt else 0}\t{ty}")
        for d in e["derived"]:
            lines.append(f"D\t{d}")
        for i in e["inverse"]:
            lines.append(f"I\t{i}")
    return "\n".join(lines) + "\n"


def render_datatypes(md: str) -> str:
    lines = [HEADER.format(source=SOURCES["DataTypes.md"][0]).rstrip("\n"),
             "# <dataType> <schemas it is valid in, comma-separated> <xs base type or ->"]
    n = 0
    for row in md.splitlines():
        if not row.startswith("| IFC"):
            continue
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        name, c2x3, c4, c4x3, base = cells[:5]
        schemas = [s for s, c in (("IFC2X3", c2x3), ("IFC4", c4), ("IFC4X3_ADD2", c4x3)) if c]
        lines.append(f"{name}\t{','.join(schemas)}\t{base or '-'}")
        n += 1
    if n < 300:
        raise SystemExit(f"DataTypes.md: only {n} data types parsed")
    return "\n".join(lines) + "\n"


def render_type_map(md: str) -> str:
    lines = [HEADER.format(source=SOURCES["ifc2x3-occurrence-type-mapping-table.md"][0]).rstrip("\n"),
             "# <name in an IDS entity facet> <IFC2X3 occurrence entity> <IFC2X3 type entity>"]
    n = 0
    for row in md.splitlines():
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        if len(cells) == 3 and all(c.startswith("Ifc") for c in cells):
            lines.append("\t".join(cells))
            n += 1
    if n < 50:
        raise SystemExit(f"type mapping table: only {n} rows parsed")
    return "\n".join(lines) + "\n"


def render_units(md: str) -> str:
    lines = [HEADER.format(source=SOURCES["units.md"][0]).rstrip("\n"),
             "# <measure> <unit type it is converted from: IfcUnitEnum or IfcDerivedUnitEnum value> <SI dimensional exponents>"]
    n = 0
    for row in md.splitlines():
        if not row.startswith("| IFC"):
            continue
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        measure, exps, unit_enum = cells[0], cells[5], cells[6]
        m = re.match(r"^Ifc(?:Derived)?UnitEnum\.(\w+)$", unit_enum)
        if not m:
            continue
        exps = re.sub(r"\s", "", exps)
        lines.append(f"{measure}\t{m.group(1)}\t{exps}")
        n += 1
    if n < 60:
        raise SystemExit(f"units.md: only {n} measures parsed")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    sources_dir = None
    if "--sources" in argv:
        sources_dir = Path(argv[argv.index("--sources") + 1])
    outputs: dict[str, str] = {}
    for schema, file in SCHEMAS:
        types, entities = parse_schema(fetch(file, sources_dir))
        if len(entities) < 600:
            raise SystemExit(f"{file}: only {len(entities)} entities parsed")
        outputs[f"{schema}.txt"] = render_schema(schema, SOURCES[file][0], types, entities)
    outputs["ids_datatypes.txt"] = render_datatypes(fetch("DataTypes.md", sources_dir))
    outputs["ifc2x3_type_map.txt"] = render_type_map(fetch("ifc2x3-occurrence-type-mapping-table.md", sources_dir))
    outputs["ids_units.txt"] = render_units(fetch("units.md", sources_dir))
    if "--check" in argv:
        stale = [n for n, t in outputs.items() if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != t]
        for n in stale:
            print(f"STALE: src/ifc/schema/{n}")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for n, t in outputs.items():
        (OUT / n).write_text(t, encoding="utf-8")
        print(f"wrote src/ifc/schema/{n} ({len(t.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
