#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# install-git-hooks.sh — install the opt-in perf pre-push hook.
#
# Drops a thin shim into this repo's git hooks dir that execs the tracked logic
# in scripts/hooks/pre-push. Idempotent and non-destructive: if a foreign
# pre-push hook already exists it's backed up to pre-push.bak first.
#
# Run once after cloning:   bash scripts/install-git-hooks.sh
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

# Marker we write into our shim so we can recognise our own installs.
MARKER="# open-triplestore perf hook"

repo_root="$(git rev-parse --show-toplevel)"
# Resolve the real hooks dir (honours core.hooksPath, worktrees, …). It may be
# relative to the repo root, so anchor it there.
hooks_dir="$(git rev-parse --git-path hooks)"
case "$hooks_dir" in
  /*|[A-Za-z]:[\\/]*) : ;;            # already absolute (POSIX or Windows drive)
  *) hooks_dir="$repo_root/$hooks_dir" ;;
esac
mkdir -p "$hooks_dir"

hook_path="$hooks_dir/pre-push"
tracked="scripts/hooks/pre-push"

# Back up any pre-existing hook that isn't already ours.
if [ -e "$hook_path" ] && ! grep -qF "$MARKER" "$hook_path" 2>/dev/null; then
  echo "⚠ Existing pre-push hook found at $hook_path — backing it up to ${hook_path}.bak"
  mv "$hook_path" "${hook_path}.bak"
fi

# Write the shim: find the repo root at run time and exec the tracked script so
# the logic stays version-controlled and editable in one place.
cat > "$hook_path" <<EOF
#!/usr/bin/env bash
$MARKER
# Auto-generated by scripts/install-git-hooks.sh — do not edit; edit
# $tracked instead, then re-run the installer.
set -euo pipefail
root="\$(git rev-parse --show-toplevel)"
exec "\$root/$tracked" "\$@"
EOF
chmod +x "$hook_path"

echo "✓ Installed perf pre-push hook → $hook_path"
echo "    (execs $tracked)"
echo ""
echo "Usage:"
echo "  • Default push runs a quick perf smoke bench on Linux/macOS; on Windows"
echo "    it's a no-op unless OTS_PERF_DOCKER=1 (CI is the authoritative gate)."
echo "  • Stricter local gate:   OTS_PERF_FULL=1 git push"
echo "  • Skip just the perf check:   SKIP_PERF=1 git push"
echo "  • Bypass all git hooks:   git push --no-verify"
echo "  • Uninstall:   rm \"$hook_path\""
