//! Seed the bundled public "Open Triplestore" demo organisation.
//!
//! On first run this creates a public organisation that owns one dataset per
//! standards category (Core RDF & SPARQL, Reasoning, Spatial, Validation, Rules,
//! Linked Data & Catalog, Capabilities). Each dataset holds one named graph per
//! standard — loaded through a mix of RDF serializations (Turtle, N-Triples,
//! RDF/XML, JSON-LD, and a SPARQL-star update) to exercise the parsers — plus
//! saved queries that demonstrate every query-able standard. The data and query
//! definitions live in [`super::seed_data`].
//!
//! Protocol and auth standards (SPARQL Update, Graph Store HTTP, Service
//! Description, LDP, DCAT/VoID, SHACL-C, JWT, OAuth/OIDC) can't be shown with a
//! SPARQL query; they are advertised in the `capabilities` dataset and verified
//! by the e2e suite against the live endpoints.
//!
//! Idempotent: skips entirely once the `open-triplestore` organisation exists,
//! so it never duplicates on restart. Best-effort — a failure loading one graph
//! or creating one service is logged and skipped without aborting the rest. Opt
//! out with `SEED_STANDARDS_DEMO=false`.

use bytes::Bytes;
use uuid::Uuid;

use crate::auth::models::{OwnerType, Role, SystemRole, Visibility};
use crate::auth::{dataset_graph, org_graph};
use crate::server::AppState;

use super::metadata;
use super::models::QueryScope;
use super::seed_data::{self, Fmt, GraphSpec, DEMO_BASE, ORG_NAME, ORG_SLUG};
use super::store::SavedQueryStore;

const ORG_DESCRIPTION: &str =
    "Public reference deployment showcasing every standard Open Triplestore implements: \
     RDF 1.1/1.2, SPARQL 1.1/1.2, RDFS, OWL 2 (QL/EL/RL/DL), GeoSPARQL, SHACL, ShEx, SWRL, \
     LDP and DCAT — each with a browsable dataset and runnable saved queries.";

/// Branded artwork for the bundled demo organisation, applied at seed time so
/// the public org page ships with a logo + header instead of a blank card. The
/// mark is the Open Triplestore knowledge-graph motif (teal "O" ring + three
/// nodes); PNG, because the image-upload allow-list rejects SVG. Regenerate
/// with `scripts/gen_org_brand.py`. Bundled into the binary like the seed docs.
const ORG_LOGO_PNG: &[u8] = include_bytes!("../../docs/assets/org-logo.png");
const ORG_BANNER_PNG: &[u8] = include_bytes!("../../docs/assets/org-banner.png");

/// Branded artwork for each bundled demo dataset, applied at seed time so the
/// public dataset pages ship with a themed icon + a custom animated banner. The
/// PNG icon is generated by `scripts/gen_dataset_brand.py`; the banner is a
/// `preset:<id>` referencing the frontend banner registry
/// (`frontend/src/lib/banners.ts`), so the animated banner needs no raster.
struct DatasetBrand {
    slug: &'static str,
    image_png: &'static [u8],
    banner_preset: &'static str,
}

const DATASET_BRANDS: &[DatasetBrand] = &[
    DatasetBrand {
        slug: "core-rdf-sparql",
        image_png: include_bytes!("../../docs/assets/dataset-brand/core-rdf-sparql.png"),
        banner_preset: "aurora-teal",
    },
    DatasetBrand {
        slug: "reasoning",
        image_png: include_bytes!("../../docs/assets/dataset-brand/reasoning.png"),
        banner_preset: "aurora-amber",
    },
    DatasetBrand {
        slug: "spatial",
        image_png: include_bytes!("../../docs/assets/dataset-brand/spatial.png"),
        banner_preset: "aurora-emerald",
    },
    DatasetBrand {
        slug: "validation",
        image_png: include_bytes!("../../docs/assets/dataset-brand/validation.png"),
        banner_preset: "aurora-violet",
    },
    DatasetBrand {
        slug: "rules",
        image_png: include_bytes!("../../docs/assets/dataset-brand/rules.png"),
        banner_preset: "aurora-azure",
    },
    DatasetBrand {
        slug: "linked-data",
        image_png: include_bytes!("../../docs/assets/dataset-brand/linked-data.png"),
        banner_preset: "aurora-cyan",
    },
    DatasetBrand {
        slug: "capabilities",
        image_png: include_bytes!("../../docs/assets/dataset-brand/capabilities.png"),
        banner_preset: "aurora-rose",
    },
    DatasetBrand {
        slug: "ots-ontology",
        image_png: include_bytes!("../../docs/assets/dataset-brand/ots-ontology.png"),
        banner_preset: "aurora-indigo",
    },
];

/// Entry point — best-effort, never panics out of startup.
pub fn seed_open_triplestore(state: &AppState) {
    let disabled = std::env::var("SEED_STANDARDS_DEMO")
        .map(|v| {
            matches!(
                v.trim().to_ascii_lowercase().as_str(),
                "false" | "0" | "no" | "off"
            )
        })
        .unwrap_or(false);
    if disabled {
        return;
    }
    if let Err(e) = try_seed(state) {
        tracing::warn!("open-triplestore demo seed skipped: {e}");
    }
}

fn try_seed(state: &AppState) -> anyhow::Result<()> {
    // Owner of the demo content: a super_admin (preferred) or any active admin.
    // On a brand-new install before any admin exists, skip quietly — the boot
    // seeder retries on the next start, once the first user (who is promoted to
    // super_admin on registration) exists.
    let owner = {
        let users = state.auth_db.list_users()?;
        users
            .iter()
            .find(|u| matches!(u.role, SystemRole::SuperAdmin) && u.is_active)
            .or_else(|| users.iter().find(|u| u.role.is_admin() && u.is_active))
            .cloned()
    };
    let owner = match owner {
        Some(u) => u,
        None => {
            tracing::info!("open-triplestore seed: no admin user yet; will retry on next start");
            return Ok(());
        }
    };

    // Resolve or create the public demo organisation. We deliberately do NOT bail
    // out when it already exists: an earlier boot may have created the org and
    // registered the demo graphs but failed to load their triples (an interrupted
    // or lock-contended seed), leaving registered-but-empty public graphs that read
    // as "no data" to logged-out users. So the whole seed runs idempotently every
    // boot and back-fills whatever is missing, without ever clobbering admin edits.
    let org_id = match state.auth_db.get_organisation_by_slug(ORG_SLUG)? {
        Some(existing) => {
            // Back-fill org branding for installs seeded before branding shipped.
            seed_org_branding(
                state,
                &existing.id,
                existing.image_key.is_none(),
                existing.banner_key.is_none(),
            );
            existing.id
        }
        None => {
            let org_id = Uuid::new_v4().to_string();
            let org = state.auth_db.create_organisation(
                &org_id,
                ORG_NAME,
                ORG_SLUG,
                Some(ORG_DESCRIPTION),
                None,
            )?;
            let _ = state
                .auth_db
                .add_org_member(&owner.id, &org_id, Role::Admin);
            org_graph::write_org_metadata_graph(&state.store, &state.base_url, &org, &[]);
            // Give the public org page a branded logo + banner out of the box.
            seed_org_branding(state, &org_id, true, true);
            org_id
        }
    };

    let sq = SavedQueryStore::new(state.auth_db.pool());
    let mut graph_count = 0usize;
    let mut backfilled = 0usize;
    let mut service_count = 0usize;

    for ds in seed_data::datasets() {
        // Use the curated, URL-safe slug as the dataset id so the minted IRI
        // (`{base}/dataset/{id}`) is human-readable — e.g. `…/dataset/spatial`
        // rather than `…/dataset/<uuid>`. Slugs are unique across the demo set.
        let ds_id = ds.slug.to_string();
        let existed = matches!(state.auth_db.get_dataset(&ds_id), Ok(Some(_)));
        if !existed {
            if let Err(e) = state.auth_db.create_dataset(
                &ds_id,
                ds.name,
                Some(ds.description),
                OwnerType::Organisation,
                &org_id,
                Visibility::Public,
                None,
            ) {
                tracing::warn!(
                    "open-triplestore seed: dataset '{}' create failed: {e}",
                    ds.slug
                );
                continue;
            }
            // Themed icon + animated banner preset so the public page isn't blank.
            seed_dataset_branding(state, &ds_id, ds.slug, true, true);
        }

        for g in ds.graphs {
            let graph_iri = format!("{DEMO_BASE}/{}/{}", ds.slug, g.suffix);
            // (Re)load the bundled data only when the target graph is empty: either a
            // fresh seed, or a previous seed that registered the graph but never
            // populated it. A graph that already holds triples is left untouched, so
            // an admin's edits to demo data are never overwritten.
            let is_empty = state
                .store
                .graph_count_cached(Some(&graph_iri))
                .unwrap_or(0)
                == 0;
            if is_empty {
                if let Err(e) = load_graph(state, &graph_iri, g) {
                    tracing::warn!("open-triplestore seed: graph <{graph_iri}> load failed: {e}");
                    continue;
                }
                if existed {
                    backfilled += 1;
                }
            }
            let _ = state.auth_db.add_dataset_graph(&ds_id, &graph_iri);
            let _ = state
                .auth_db
                .set_dataset_graph_role(&ds_id, &graph_iri, Some(g.role));
            graph_count += 1;
        }

        // Project the dataset's DCAT/VoID metadata graph so it is discoverable
        // as linked data (mirrors what the bulk-import path does).
        if let Ok(Some(dsrec)) = state.auth_db.get_dataset(&ds_id) {
            let entries = state
                .auth_db
                .list_dataset_graph_entries(&ds_id)
                .unwrap_or_default();
            dataset_graph::write_dataset_metadata_graph(
                &state.store,
                &state.base_url,
                &dsrec,
                &entries,
            );
        }

        // Saved-query services — create only when the dataset has none yet, so a
        // reseed on every boot doesn't pile up duplicate services.
        let has_services = sq
            .list(QueryScope::Dataset, &ds_id)
            .map(|v| !v.is_empty())
            .unwrap_or(false);
        if !has_services {
            for req in seed_data::services_for(ds.slug) {
                match sq.create(QueryScope::Dataset, &ds_id, &req, &owner.id) {
                    Ok(svc) => {
                        metadata::record_service(&state.store, &state.base_url, &svc);
                        metadata::record_revision(
                            &state.store,
                            &state.base_url,
                            &svc.id,
                            svc.current_revision,
                            req.version_name.as_deref(),
                            req.note.as_deref(),
                            svc.sparql.as_deref().unwrap_or(&req.sparql),
                            "manual",
                            &svc.created_by,
                            &svc.created_at,
                        );
                        service_count += 1;
                    }
                    Err(e) => {
                        tracing::warn!("open-triplestore seed: service '{}' failed: {e}", req.name)
                    }
                }
            }
        }
    }

    // The Schependomlaan IFC (layered Dutch BIM demo) is downloaded + converted
    // on first boot — and back-filled on later boots if a download once failed.
    seed_schependomlaan_ifc(state, &owner.id);

    #[cfg(feature = "text-search")]
    state.mark_text_dirty();

    // Back-filled graph data changes what each principal can see/count, so drop the
    // accessible-graph cache to reflect it immediately rather than after the TTL.
    if backfilled > 0 {
        state.auth_db.invalidate_accessible_graphs_cache();
    }

    tracing::info!(
        "Seeded/verified '{}' organisation ({}): {} datasets, {} graphs ({} back-filled), {} new services",
        ORG_NAME,
        org_id,
        seed_data::datasets().len(),
        graph_count,
        backfilled,
        service_count
    );
    Ok(())
}

/// Default source of the Schependomlaan design-model IFC — the canonical open
/// Dutch BIM dataset (Nijmegen; CC BY 4.0, openBIMstandards/TU Eindhoven),
/// mirrored on GitHub. Override with `SEED_IFC_URL`; disable the whole demo
/// seed with `SEED_STANDARDS_DEMO=false`.
const SCHEPENDOMLAAN_IFC_URL: &str = "https://raw.githubusercontent.com/jakob-beetz/DataSetSchependomlaan/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc";

/// Download the Schependomlaan IFC (~49 MB, first boot only) and run it through
/// the same IFC import pipeline users get: stored as a public dataset asset,
/// converted to a BOT topology graph + a full ifcOWL lift, every storey, wall
/// and beam individually addressable. Skips instantly when the building graph
/// already has data; a failed download just retries on the next boot.
fn seed_schependomlaan_ifc(state: &AppState, owner_id: &str) {
    const DS: &str = "viewer-3d-demo";
    let bot_graph = format!("{}/{}/building", seed_data::DEMO_BASE, DS);
    if state
        .store
        .graph_count_cached(Some(&bot_graph))
        .unwrap_or(0)
        > 0
    {
        return;
    }
    if !matches!(state.auth_db.get_dataset(DS), Ok(Some(_))) {
        return;
    }
    let url = std::env::var("SEED_IFC_URL").unwrap_or_else(|_| SCHEPENDOMLAAN_IFC_URL.to_string());
    // An explicitly empty SEED_IFC_URL disables the IFC demo (also used by
    // tests, which must never reach out to the network).
    if url.trim().is_empty() {
        tracing::info!("SEED_IFC_URL is empty — skipping the Schependomlaan IFC demo");
        return;
    }
    tracing::info!("seed: downloading Schependomlaan IFC ({url}) — first boot only");
    // We're on a blocking thread (the seed runs in spawn_blocking), so driving
    // the async download + import with block_on is safe here.
    let handle = tokio::runtime::Handle::current();
    let bytes = match handle.block_on(async {
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(600))
            .build()?;
        client
            .get(&url)
            .send()
            .await?
            .error_for_status()?
            .bytes()
            .await
    }) {
        Ok(b) => b.to_vec(),
        Err(e) => {
            tracing::warn!(
                "schependomlaan seed skipped (download failed, will retry next boot): {e}"
            );
            return;
        }
    };
    match handle.block_on(crate::imports::ifc::import_ifc_bytes(
        state,
        DS,
        owner_id,
        "Schependomlaan.ifc",
        bytes,
        Some(bot_graph),
        true,
        true,
        Some(url),
        // The file's IfcSite carries an exporter-default location; anchor the
        // demo at the real Schependomlaan site (PDOK street centroid) instead.
        Some("POINT(5.83373 51.84114)".to_string()),
    )) {
        Ok(o) => tracing::info!(
            "seeded Schependomlaan: {} elements / {} storeys / {} spaces; BOT {} + ifcOWL {} triples",
            o.stats.elements, o.stats.storeys, o.stats.spaces, o.stats.bot_triples, o.stats.ifcowl_triples
        ),
        Err(e) => tracing::warn!("schependomlaan seed failed: {e}"),
    }
}

/// Upload the bundled logo/banner for the demo organisation and record their
/// object keys (the same keys the upload endpoints use, so the existing
/// `GET /api/organisations/:id/{image,banner}` handlers serve them). `do_logo`
/// / `do_banner` let the caller back-fill only what's missing. Best-effort:
/// it skips silently when object storage isn't configured and logs (without
/// aborting the seed) on any failure.
fn seed_org_branding(state: &AppState, org_id: &str, do_logo: bool, do_banner: bool) {
    if !state.object_store.is_configured() || (!do_logo && !do_banner) {
        return;
    }
    // The seed runs on a blocking thread (spawn_blocking), so drive the async
    // object-store uploads to completion on the current runtime handle.
    let rt = tokio::runtime::Handle::current();
    let assets: [(bool, &str, &'static [u8]); 2] = [
        (do_logo, "org-images", ORG_LOGO_PNG),
        (do_banner, "org-banners", ORG_BANNER_PNG),
    ];
    for (wanted, prefix, bytes) in assets {
        if !wanted {
            continue;
        }
        let key = format!("{prefix}/{org_id}.png");
        if let Err(e) = rt.block_on(state.object_store.upload(
            &key,
            Bytes::from_static(bytes),
            "image/png",
        )) {
            tracing::warn!("open-triplestore seed: branding upload to '{key}' failed: {e}");
            continue;
        }
        let recorded = if prefix == "org-images" {
            state.auth_db.update_org_image(org_id, Some(&key))
        } else {
            state.auth_db.update_org_banner(org_id, Some(&key))
        };
        if let Err(e) = recorded {
            tracing::warn!("open-triplestore seed: recording branding key '{key}' failed: {e}");
        }
    }
}

/// Back-fill the themed icon + animated banner preset for one bundled demo
/// dataset (matched by `slug`). `do_image`/`do_banner` let the caller fill only
/// what's currently unset, so it never clobbers artwork an admin has chosen. The
/// banner preset is a DB-only sentinel (`preset:<id>`); the icon upload is
/// skipped silently when object storage isn't configured. Best-effort — failures
/// are logged, never fatal to the seed.
fn seed_dataset_branding(
    state: &AppState,
    dataset_id: &str,
    slug: &str,
    do_image: bool,
    do_banner: bool,
) {
    let Some(brand) = DATASET_BRANDS.iter().find(|b| b.slug == slug) else {
        return;
    };
    if do_banner {
        let key = format!("preset:{}", brand.banner_preset);
        if let Err(e) = state.auth_db.update_dataset_banner(dataset_id, Some(&key)) {
            tracing::warn!("open-triplestore seed: dataset banner preset for '{slug}' failed: {e}");
        }
    }
    if do_image && state.object_store.is_configured() {
        let rt = tokio::runtime::Handle::current();
        let key = format!("dataset-images/{dataset_id}.png");
        match rt.block_on(state.object_store.upload(
            &key,
            Bytes::from_static(brand.image_png),
            "image/png",
        )) {
            Ok(()) => {
                if let Err(e) = state.auth_db.update_dataset_image(dataset_id, Some(&key)) {
                    tracing::warn!(
                        "open-triplestore seed: recording dataset image key '{key}' failed: {e}"
                    );
                }
            }
            Err(e) => {
                tracing::warn!("open-triplestore seed: dataset image upload to '{key}' failed: {e}")
            }
        }
    }
}

/// Load one graph's bundled data into its named graph. Quoted-triple data is
/// loaded through a SPARQL-star `INSERT DATA`; everything else goes through the
/// Graph Store PUT path in its declared serialization.
fn load_graph(state: &AppState, graph_iri: &str, g: &GraphSpec) -> anyhow::Result<()> {
    match g.fmt {
        Fmt::SparqlStarUpdate => {
            state
                .store
                .update(&format!(
                    "INSERT DATA {{ GRAPH <{graph_iri}> {{ {} }} }}",
                    g.data
                ))
                .map_err(|e| anyhow::anyhow!("{e}"))?;
        }
        other => {
            let format = other
                .rdf_format()
                .expect("non-update formats always map to an RdfFormat");
            state
                .store
                .graph_store_put(Some(graph_iri), g.data, format)
                .map_err(|e| anyhow::anyhow!("{e}"))?;
        }
    }
    Ok(())
}
