//! Seed the bundled public "Open Triplestore" demo organisation.
//!
//! On first run this creates a public organisation that owns one dataset per
//! standards category (Core RDF & SPARQL, Reasoning, Spatial, Validation, Rules,
//! Linked Data & Catalog, Capabilities). Each dataset holds one named graph per
//! standard — loaded through a mix of RDF serializations (Turtle, N-Triples,
//! RDF/XML, JSON-LD, and a SPARQL-star update) to exercise the parsers — plus
//! saved queries that demonstrate every query-able standard. The data and query
//! definitions live in [`super::seed_data`].
//!
//! Protocol and auth standards (SPARQL Update, Graph Store HTTP, Service
//! Description, LDP, DCAT/VoID, SHACL-C, JWT, OAuth/OIDC) can't be shown with a
//! SPARQL query; they are advertised in the `capabilities` dataset and verified
//! by the e2e suite against the live endpoints.
//!
//! Idempotent: skips entirely once the `open-triplestore` organisation exists,
//! so it never duplicates on restart. Best-effort — a failure loading one graph
//! or creating one service is logged and skipped without aborting the rest. Opt
//! out with `SEED_STANDARDS_DEMO=false`.

use bytes::Bytes;
use uuid::Uuid;

use crate::auth::models::{OwnerType, Role, SystemRole, Visibility};
use crate::auth::{dataset_graph, org_graph};
use crate::server::AppState;

use super::metadata;
use super::models::QueryScope;
use super::seed_data::{self, Fmt, GraphSpec, DEMO_BASE, ORG_NAME, ORG_SLUG};
use super::store::SavedQueryStore;

const ORG_DESCRIPTION: &str =
    "Public reference deployment showcasing every standard Open Triplestore implements: \
     RDF 1.1/1.2, SPARQL 1.1/1.2, RDFS, OWL 2 (QL/EL/RL/DL), GeoSPARQL, SHACL, ShEx, SWRL, \
     LDP and DCAT — each with a browsable dataset and runnable saved queries.";

/// Branded artwork for the bundled demo organisation, applied at seed time so
/// the public org page ships with a logo + header instead of a blank card. The
/// mark is the Open Triplestore knowledge-graph motif (teal "O" ring + three
/// nodes); PNG, because the image-upload allow-list rejects SVG. Regenerate
/// with `scripts/gen_org_brand.py`. Bundled into the binary like the seed docs.
const ORG_LOGO_PNG: &[u8] = include_bytes!("../../docs/assets/org-logo.png");
const ORG_BANNER_PNG: &[u8] = include_bytes!("../../docs/assets/org-banner.png");

/// Branded artwork for each bundled demo dataset, applied at seed time so the
/// public dataset pages ship with a themed icon + a custom animated banner. The
/// PNG icon is generated by `scripts/gen_dataset_brand.py`; the banner is a
/// `preset:<id>` referencing the frontend banner registry
/// (`frontend/src/lib/banners.ts`), so the animated banner needs no raster.
struct DatasetBrand {
    slug: &'static str,
    image_png: &'static [u8],
    banner_preset: &'static str,
}

const DATASET_BRANDS: &[DatasetBrand] = &[
    DatasetBrand {
        slug: "core-rdf-sparql",
        image_png: include_bytes!("../../docs/assets/dataset-brand/core-rdf-sparql.png"),
        banner_preset: "aurora-teal",
    },
    DatasetBrand {
        slug: "reasoning",
        image_png: include_bytes!("../../docs/assets/dataset-brand/reasoning.png"),
        banner_preset: "aurora-amber",
    },
    DatasetBrand {
        slug: "spatial",
        image_png: include_bytes!("../../docs/assets/dataset-brand/spatial.png"),
        banner_preset: "aurora-emerald",
    },
    DatasetBrand {
        slug: "validation",
        image_png: include_bytes!("../../docs/assets/dataset-brand/validation.png"),
        banner_preset: "aurora-violet",
    },
    DatasetBrand {
        slug: "rules",
        image_png: include_bytes!("../../docs/assets/dataset-brand/rules.png"),
        banner_preset: "aurora-azure",
    },
    DatasetBrand {
        slug: "linked-data",
        image_png: include_bytes!("../../docs/assets/dataset-brand/linked-data.png"),
        banner_preset: "aurora-cyan",
    },
    DatasetBrand {
        slug: "capabilities",
        image_png: include_bytes!("../../docs/assets/dataset-brand/capabilities.png"),
        banner_preset: "aurora-rose",
    },
    DatasetBrand {
        slug: "ots-ontology",
        image_png: include_bytes!("../../docs/assets/dataset-brand/ots-ontology.png"),
        banner_preset: "aurora-indigo",
    },
];

/// Entry point — best-effort, never panics out of startup.
pub fn seed_open_triplestore(state: &AppState) {
    let disabled = std::env::var("SEED_STANDARDS_DEMO")
        .map(|v| {
            matches!(
                v.trim().to_ascii_lowercase().as_str(),
                "false" | "0" | "no" | "off"
            )
        })
        .unwrap_or(false);
    if disabled {
        return;
    }
    // Two seeders can run concurrently on a fresh install: the boot task only
    // reaches the demo seed after the SHACL/standards seeding (seconds), and the
    // first-admin registration handler kicks one off the moment that admin
    // exists — the browser-e2e harness registers its admin exactly in that
    // window. The seed is idempotent but not concurrent with itself: both
    // passes see "missing", then race their INSERTs into UNIQUE constraints
    // (and both would download the demo IFC). Serialise process-wide; the
    // second pass then no-ops via the existence checks.
    static SEED_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let _guard = SEED_LOCK.lock().unwrap_or_else(|p| p.into_inner());
    if let Err(e) = try_seed(state) {
        tracing::warn!("open-triplestore demo seed skipped: {e}");
    }
}

fn try_seed(state: &AppState) -> anyhow::Result<()> {
    // Owner of the *owner-attributed* demo content (saved-query services, the IFC
    // import, org membership): a super_admin (preferred) or any active admin.
    //
    // The organisation itself and all its PUBLIC data — datasets, named graphs,
    // metadata, branding — are created regardless of whether an admin exists yet,
    // so on a brand-new install they appear on first boot, before anyone has
    // registered, and logged-out visitors see the public demo immediately. Only
    // the content that must be attributed to a user waits: it is back-filled
    // idempotently once the first admin exists (the registration handler reseeds,
    // and every boot reseeds anyway).
    let owner = {
        let users = state.auth_db.list_users()?;
        users
            .iter()
            .find(|u| matches!(u.role, SystemRole::SuperAdmin) && u.is_active)
            .or_else(|| users.iter().find(|u| u.role.is_admin() && u.is_active))
            .cloned()
    };

    // Resolve or create the public demo organisation. We deliberately do NOT bail
    // out when it already exists: an earlier boot may have created the org and
    // registered the demo graphs but failed to load their triples (an interrupted
    // or lock-contended seed), leaving registered-but-empty public graphs that read
    // as "no data" to logged-out users. So the whole seed runs idempotently every
    // boot and back-fills whatever is missing, without ever clobbering admin edits.
    let org_id = match state.auth_db.get_organisation_by_slug(ORG_SLUG)? {
        Some(existing) => {
            // Back-fill org branding for installs seeded before branding shipped.
            seed_org_branding(
                state,
                &existing.id,
                existing.image_key.is_none(),
                existing.banner_key.is_none(),
            );
            existing.id
        }
        None => {
            let org_id = Uuid::new_v4().to_string();
            let org = state.auth_db.create_organisation(
                &org_id,
                ORG_NAME,
                ORG_SLUG,
                Some(ORG_DESCRIPTION),
                None,
            )?;
            org_graph::write_org_metadata_graph(&state.store, &state.base_url, &org, &[]);
            // Give the public org page a branded logo + banner out of the box.
            seed_org_branding(state, &org_id, true, true);
            org_id
        }
    };

    // Make the first admin an Admin member of the org. Idempotent (INSERT OR
    // REPLACE), so it's safe whether we just created the org or are back-filling
    // membership on a later reseed once the first admin exists. Skipped entirely
    // on a brand-new install with no users yet — the org stands member-less until
    // then, which is fine for a public demo org.
    if let Some(ref owner) = owner {
        let _ = state
            .auth_db
            .add_org_member(&owner.id, &org_id, Role::Admin);
    }

    let sq = SavedQueryStore::new(state.auth_db.pool());
    let mut graph_count = 0usize;
    let mut backfilled = 0usize;
    let mut service_count = 0usize;

    for ds in seed_data::datasets() {
        // Use the curated, URL-safe slug as the dataset id so the minted IRI
        // (`{base}/dataset/{id}`) is human-readable — e.g. `…/dataset/spatial`
        // rather than `…/dataset/<uuid>`. Slugs are unique across the demo set.
        let ds_id = ds.slug.to_string();
        let existed = matches!(state.auth_db.get_dataset(&ds_id), Ok(Some(_)));
        if !existed {
            if let Err(e) = state.auth_db.create_dataset(
                &ds_id,
                ds.name,
                Some(ds.description),
                OwnerType::Organisation,
                &org_id,
                Visibility::Public,
                None,
            ) {
                tracing::warn!(
                    "open-triplestore seed: dataset '{}' create failed: {e}",
                    ds.slug
                );
                continue;
            }
            // Themed icon + animated banner preset so the public page isn't blank.
            seed_dataset_branding(state, &ds_id, ds.slug, true, true);
        }

        for g in ds.graphs {
            let graph_iri = format!("{DEMO_BASE}/{}/{}", ds.slug, g.suffix);
            // (Re)load the bundled data only when the target graph is empty: either a
            // fresh seed, or a previous seed that registered the graph but never
            // populated it. A graph that already holds triples is left untouched, so
            // an admin's edits to demo data are never overwritten.
            let is_empty = state
                .store
                .graph_count_cached(Some(&graph_iri))
                .unwrap_or(0)
                == 0;
            if is_empty {
                if let Err(e) = load_graph(state, &graph_iri, g) {
                    tracing::warn!("open-triplestore seed: graph <{graph_iri}> load failed: {e}");
                    continue;
                }
                if existed {
                    backfilled += 1;
                }
            }
            let _ = state.auth_db.add_dataset_graph(&ds_id, &graph_iri);
            let _ = state
                .auth_db
                .set_dataset_graph_role(&ds_id, &graph_iri, Some(g.role));
            graph_count += 1;
        }

        // Project the dataset's DCAT/VoID metadata graph so it is discoverable
        // as linked data (mirrors what the bulk-import path does).
        if let Ok(Some(dsrec)) = state.auth_db.get_dataset(&ds_id) {
            let entries = state
                .auth_db
                .list_dataset_graph_entries(&ds_id)
                .unwrap_or_default();
            dataset_graph::write_dataset_metadata_graph(
                &state.store,
                &state.base_url,
                &dsrec,
                &entries,
            );
        }

        // Saved-query services are attributed to the owning admin, so they wait
        // until one exists (back-filled on the reseed after the first admin
        // registers). Create only when the dataset has none yet, so a reseed on
        // every boot doesn't pile up duplicate services.
        if let Some(ref owner) = owner {
            let has_services = sq
                .list(QueryScope::Dataset, &ds_id)
                .map(|v| !v.is_empty())
                .unwrap_or(false);
            if !has_services {
                for req in seed_data::services_for(ds.slug) {
                    match sq.create(QueryScope::Dataset, &ds_id, &req, &owner.id) {
                        Ok(svc) => {
                            metadata::record_service(&state.store, &state.base_url, &svc);
                            metadata::record_revision(
                                &state.store,
                                &state.base_url,
                                &svc.id,
                                svc.current_revision,
                                req.version_name.as_deref(),
                                req.note.as_deref(),
                                svc.sparql.as_deref().unwrap_or(&req.sparql),
                                "manual",
                                &svc.created_by,
                                &svc.created_at,
                            );
                            service_count += 1;
                        }
                        Err(e) => {
                            tracing::warn!(
                                "open-triplestore seed: service '{}' failed: {e}",
                                req.name
                            )
                        }
                    }
                }
            }
        }
    }

    // The Schependomlaan IFC (layered Dutch BIM demo) is attributed to the owning
    // admin, so it waits until one exists; downloaded + converted on the first
    // boot/reseed after that, and back-filled on later boots if a download failed.
    if let Some(ref owner) = owner {
        seed_schependomlaan_ifc(state, &owner.id);
    }

    #[cfg(feature = "text-search")]
    state.mark_text_dirty();

    // Back-filled graph data changes what each principal can see/count, so drop the
    // accessible-graph cache to reflect it immediately rather than after the TTL.
    if backfilled > 0 {
        state.auth_db.invalidate_accessible_graphs_cache();
    }

    tracing::info!(
        "Seeded/verified '{}' organisation ({}): {} datasets, {} graphs ({} back-filled), {} new services",
        ORG_NAME,
        org_id,
        seed_data::datasets().len(),
        graph_count,
        backfilled,
        service_count
    );
    if owner.is_none() {
        tracing::info!(
            "open-triplestore seed: org + public data created on first load; saved-query \
             services, the IFC demo and org membership are deferred until the first admin registers"
        );
    }
    Ok(())
}

/// Drive `fut` to completion from any calling context. The seed normally runs
/// on a `spawn_blocking` thread, where `Handle::current().block_on` would be
/// fine — but tests call it straight from async workers, where that panics
/// ("Cannot start a runtime from within a runtime"). A throwaway
/// single-thread runtime on a scoped OS thread works from both.
fn block_on_anywhere<T: Send>(
    fut: impl std::future::Future<Output = T> + Send,
) -> anyhow::Result<T> {
    std::thread::scope(|scope| {
        scope
            .spawn(|| {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()?;
                Ok(rt.block_on(fut))
            })
            .join()
            .unwrap_or_else(|panic| std::panic::resume_unwind(panic))
    })
}

/// Default source of the Schependomlaan design-model IFC — the canonical open
/// Dutch BIM dataset (Nijmegen; CC BY 4.0, openBIMstandards/TU Eindhoven),
/// mirrored on GitHub. Override with `SEED_IFC_URL`; disable the whole demo
/// seed with `SEED_STANDARDS_DEMO=false`.
const SCHEPENDOMLAAN_IFC_URL: &str = "https://raw.githubusercontent.com/jakob-beetz/DataSetSchependomlaan/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc";

/// Download the Schependomlaan IFC (~49 MB, first boot only) and run it through
/// the same IFC import pipeline users get: stored as a public dataset asset,
/// converted to a BOT topology graph + a full ifcOWL lift, every storey, wall
/// and beam individually addressable. Skips instantly when the building graph
/// already has data; a failed download just retries on the next boot.
fn seed_schependomlaan_ifc(state: &AppState, owner_id: &str) {
    const DS: &str = "viewer-3d-demo";
    let bot_graph = format!("{}/{}/building", seed_data::DEMO_BASE, DS);
    if state
        .store
        .graph_count_cached(Some(&bot_graph))
        .unwrap_or(0)
        > 0
    {
        return;
    }
    if !matches!(state.auth_db.get_dataset(DS), Ok(Some(_))) {
        return;
    }
    let url = std::env::var("SEED_IFC_URL").unwrap_or_else(|_| SCHEPENDOMLAAN_IFC_URL.to_string());
    // An explicitly empty SEED_IFC_URL disables the IFC demo (also used by
    // tests, which must never reach out to the network).
    if url.trim().is_empty() {
        tracing::info!("SEED_IFC_URL is empty — skipping the Schependomlaan IFC demo");
        return;
    }
    tracing::info!("seed: downloading Schependomlaan IFC ({url}) — first boot only");
    let downloaded = block_on_anywhere(async {
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(600))
            .build()?;
        let bytes = client
            .get(&url)
            .send()
            .await?
            .error_for_status()?
            .bytes()
            .await?;
        anyhow::Ok(bytes.to_vec())
    })
    .and_then(|r| r);
    let bytes = match downloaded {
        Ok(b) => b,
        Err(e) => {
            tracing::warn!(
                "schependomlaan seed skipped (download failed, will retry next boot): {e}"
            );
            return;
        }
    };
    let imported = block_on_anywhere(crate::imports::ifc::import_ifc_bytes(
        state,
        DS,
        owner_id,
        "Schependomlaan.ifc",
        bytes,
        Some(bot_graph),
        true,
        true,
        Some(url),
        // The file's IfcSite carries an exporter-default location; anchor the
        // demo at the real Schependomlaan site (PDOK street centroid) instead.
        Some("POINT(5.83373 51.84114)".to_string()),
    ))
    .and_then(|r| r.map_err(anyhow::Error::msg));
    match imported {
        Ok(o) => tracing::info!(
            "seeded Schependomlaan: {} elements / {} storeys / {} spaces; BOT {} + ifcOWL {} triples",
            o.stats.elements, o.stats.storeys, o.stats.spaces, o.stats.bot_triples, o.stats.ifcowl_triples
        ),
        Err(e) => tracing::warn!("schependomlaan seed failed: {e}"),
    }
}

/// Upload the bundled logo/banner for the demo organisation and record their
/// object keys (the same keys the upload endpoints use, so the existing
/// `GET /api/organisations/:id/{image,banner}` handlers serve them). `do_logo`
/// / `do_banner` let the caller back-fill only what's missing. Best-effort:
/// it skips silently when object storage isn't configured and logs (without
/// aborting the seed) on any failure.
fn seed_org_branding(state: &AppState, org_id: &str, do_logo: bool, do_banner: bool) {
    if !state.object_store.is_configured() || (!do_logo && !do_banner) {
        return;
    }
    let assets: [(bool, &str, &'static [u8]); 2] = [
        (do_logo, "org-images", ORG_LOGO_PNG),
        (do_banner, "org-banners", ORG_BANNER_PNG),
    ];
    for (wanted, prefix, bytes) in assets {
        if !wanted {
            continue;
        }
        let key = format!("{prefix}/{org_id}.png");
        let uploaded = block_on_anywhere(state.object_store.upload(
            &key,
            Bytes::from_static(bytes),
            "image/png",
        ))
        .and_then(|r| r);
        if let Err(e) = uploaded {
            tracing::warn!("open-triplestore seed: branding upload to '{key}' failed: {e}");
            continue;
        }
        let recorded = if prefix == "org-images" {
            state.auth_db.update_org_image(org_id, Some(&key))
        } else {
            state.auth_db.update_org_banner(org_id, Some(&key))
        };
        if let Err(e) = recorded {
            tracing::warn!("open-triplestore seed: recording branding key '{key}' failed: {e}");
        }
    }
}

/// Back-fill the themed icon + animated banner preset for one bundled demo
/// dataset (matched by `slug`). `do_image`/`do_banner` let the caller fill only
/// what's currently unset, so it never clobbers artwork an admin has chosen. The
/// banner preset is a DB-only sentinel (`preset:<id>`); the icon upload is
/// skipped silently when object storage isn't configured. Best-effort — failures
/// are logged, never fatal to the seed.
fn seed_dataset_branding(
    state: &AppState,
    dataset_id: &str,
    slug: &str,
    do_image: bool,
    do_banner: bool,
) {
    let Some(brand) = DATASET_BRANDS.iter().find(|b| b.slug == slug) else {
        return;
    };
    if do_banner {
        let key = format!("preset:{}", brand.banner_preset);
        if let Err(e) = state.auth_db.update_dataset_banner(dataset_id, Some(&key)) {
            tracing::warn!("open-triplestore seed: dataset banner preset for '{slug}' failed: {e}");
        }
    }
    if do_image && state.object_store.is_configured() {
        let rt = tokio::runtime::Handle::current();
        let key = format!("dataset-images/{dataset_id}.png");
        match rt.block_on(state.object_store.upload(
            &key,
            Bytes::from_static(brand.image_png),
            "image/png",
        )) {
            Ok(()) => {
                if let Err(e) = state.auth_db.update_dataset_image(dataset_id, Some(&key)) {
                    tracing::warn!(
                        "open-triplestore seed: recording dataset image key '{key}' failed: {e}"
                    );
                }
            }
            Err(e) => {
                tracing::warn!("open-triplestore seed: dataset image upload to '{key}' failed: {e}")
            }
        }
    }
}

/// Load one graph's bundled data into its named graph. Quoted-triple data is
/// loaded through a SPARQL-star `INSERT DATA`; everything else goes through the
/// Graph Store PUT path in its declared serialization.
fn load_graph(state: &AppState, graph_iri: &str, g: &GraphSpec) -> anyhow::Result<()> {
    match g.fmt {
        Fmt::SparqlStarUpdate => {
            state
                .store
                .update(&format!(
                    "INSERT DATA {{ GRAPH <{graph_iri}> {{ {} }} }}",
                    g.data
                ))
                .map_err(|e| anyhow::anyhow!("{e}"))?;
        }
        other => {
            let format = other
                .rdf_format()
                .expect("non-update formats always map to an RdfFormat");
            state
                .store
                .graph_store_put(Some(graph_iri), g.data, format)
                .map_err(|e| anyhow::anyhow!("{e}"))?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::server::AppState;
    use crate::store::TripleStore;

    /// Run the demo seed the way production does — on the blocking pool, so the
    /// branding helpers' `Handle::current().block_on` has a runtime to use and the
    /// seeder's internal `block_on`s don't panic on an async worker. An empty
    /// `SEED_IFC_URL` keeps the seeder off the network (no IFC download).
    async fn run_seed(state: &AppState) {
        std::env::set_var("SEED_IFC_URL", "");
        let s = state.clone();
        tokio::task::spawn_blocking(move || seed_open_triplestore(&s))
            .await
            .unwrap();
    }

    /// The org and all its PUBLIC data are created on first boot, before anyone
    /// has registered — the headline fix. Owner-attributed content (membership +
    /// saved-query services) is deferred until an admin exists.
    #[tokio::test]
    async fn creates_org_and_public_data_on_first_load_without_any_user() {
        let state = AppState::test_default_with_store(TripleStore::in_memory().unwrap());
        assert_eq!(state.auth_db.count_users().unwrap(), 0, "fresh install");

        run_seed(&state).await;

        let org = state
            .auth_db
            .get_organisation_by_slug(ORG_SLUG)
            .unwrap()
            .expect("org is created on first load, not first login");
        assert_eq!(org.name, ORG_NAME);

        // Every public demo dataset exists already.
        for ds in seed_data::datasets() {
            assert!(
                matches!(state.auth_db.get_dataset(ds.slug), Ok(Some(_))),
                "dataset '{}' created on first load",
                ds.slug
            );
        }

        // Owner-attributed content is deferred: no members, no services yet.
        assert!(
            state.auth_db.list_org_members(&org.id).unwrap().is_empty(),
            "org has no members until the first admin registers"
        );
        let sq = SavedQueryStore::new(state.auth_db.pool());
        for ds in seed_data::datasets() {
            assert!(
                sq.list(QueryScope::Dataset, ds.slug)
                    .unwrap_or_default()
                    .is_empty(),
                "saved-query services deferred for '{}'",
                ds.slug
            );
        }
    }

    /// Once the first admin exists, the (idempotent) reseed back-fills the
    /// owner-attributed content the first-load seed deferred.
    #[tokio::test]
    async fn backfills_membership_and_services_once_an_admin_exists() {
        let state = AppState::test_default_with_store(TripleStore::in_memory().unwrap());

        // First boot, no users: org + public data, services deferred.
        run_seed(&state).await;
        let demo_ds = seed_data::datasets()[0].slug;
        let sq = SavedQueryStore::new(state.auth_db.pool());
        assert!(
            sq.list(QueryScope::Dataset, demo_ds)
                .unwrap_or_default()
                .is_empty(),
            "no services before an admin exists"
        );

        // The first admin appears (promoted to super_admin in the real flow).
        let admin = state
            .auth_db
            .create_user(
                "admin-1",
                "admin",
                "admin@x.test",
                "hash",
                SystemRole::SuperAdmin,
            )
            .unwrap();

        // Reseed, exactly as the registration handler does on first admin.
        run_seed(&state).await;

        let org = state
            .auth_db
            .get_organisation_by_slug(ORG_SLUG)
            .unwrap()
            .unwrap();
        let members = state.auth_db.list_org_members(&org.id).unwrap();
        assert!(
            members
                .iter()
                .any(|(u, r)| u.id == admin.id && matches!(r, Role::Admin)),
            "first admin back-filled as an Admin member of the org"
        );
        assert!(
            !sq.list(QueryScope::Dataset, demo_ds)
                .unwrap_or_default()
                .is_empty(),
            "saved-query services back-filled once an owner exists"
        );
    }
}
