//! Seed the bundled public "Open Triplestore" demo organisation.
//!
//! On first run this creates a public organisation that owns one dataset per
//! standards category (Core RDF & SPARQL, Reasoning, Spatial, Validation, Rules,
//! Linked Data & Catalog, Capabilities). Each dataset holds one named graph per
//! standard — loaded through a mix of RDF serializations (Turtle, N-Triples,
//! RDF/XML, JSON-LD, and a SPARQL-star update) to exercise the parsers — plus
//! saved queries that demonstrate every query-able standard. The data and query
//! definitions live in [`super::seed_data`].
//!
//! Protocol and auth standards (SPARQL Update, Graph Store HTTP, Service
//! Description, LDP, DCAT/VoID, SHACL-C, JWT, OAuth/OIDC) can't be shown with a
//! SPARQL query; they are advertised in the `capabilities` dataset and verified
//! by the e2e suite against the live endpoints.
//!
//! Idempotent: skips entirely once the `open-triplestore` organisation exists,
//! so it never duplicates on restart. Best-effort — a failure loading one graph
//! or creating one service is logged and skipped without aborting the rest. Opt
//! out with `SEED_STANDARDS_DEMO=false`.

use std::borrow::Cow;

use bytes::Bytes;

use crate::auth::models::Visibility;
use crate::seed_bundles::{self, Bundle, BundleDataset, BundleGraph, OrgSpec};
use crate::server::AppState;

use super::seed_data::{self, DEMO_BASE, ORG_NAME, ORG_SLUG};

const ORG_DESCRIPTION: &str =
    "Public reference deployment showcasing every standard Open Triplestore implements: \
     RDF 1.1/1.2, SPARQL 1.1/1.2, RDFS, OWL 2 (QL/EL/RL/DL), GeoSPARQL, SHACL, ShEx, SWRL, \
     LDP and DCAT — each with a browsable dataset and runnable saved queries.";

/// Branded artwork for the bundled demo organisation, applied at seed time so
/// the public org page ships with a logo + header instead of a blank card. The
/// mark is the Open Triplestore knowledge-graph motif (teal "O" ring + three
/// nodes); PNG, because the image-upload allow-list rejects SVG. Regenerate
/// with `scripts/gen_org_brand.py`. Bundled into the binary like the seed docs.
const ORG_LOGO_PNG: &[u8] = include_bytes!("../../docs/assets/org-logo.png");
const ORG_BANNER_PNG: &[u8] = include_bytes!("../../docs/assets/org-banner.png");

/// Branded artwork for each bundled demo dataset, applied at seed time so the
/// public dataset pages ship with a themed icon + a custom animated banner. The
/// PNG icon is generated by `scripts/gen_dataset_brand.py`; the banner is a
/// `preset:<id>` referencing the frontend banner registry
/// (`frontend/src/lib/banners.ts`), so the animated banner needs no raster.
struct DatasetBrand {
    slug: &'static str,
    image_png: &'static [u8],
    banner_preset: &'static str,
}

const DATASET_BRANDS: &[DatasetBrand] = &[
    DatasetBrand {
        slug: "core-rdf-sparql",
        image_png: include_bytes!("../../docs/assets/dataset-brand/core-rdf-sparql.png"),
        banner_preset: "aurora-teal",
    },
    DatasetBrand {
        slug: "reasoning",
        image_png: include_bytes!("../../docs/assets/dataset-brand/reasoning.png"),
        banner_preset: "aurora-amber",
    },
    DatasetBrand {
        slug: "spatial",
        image_png: include_bytes!("../../docs/assets/dataset-brand/spatial.png"),
        banner_preset: "aurora-emerald",
    },
    DatasetBrand {
        slug: "validation",
        image_png: include_bytes!("../../docs/assets/dataset-brand/validation.png"),
        banner_preset: "aurora-violet",
    },
    DatasetBrand {
        slug: "rules",
        image_png: include_bytes!("../../docs/assets/dataset-brand/rules.png"),
        banner_preset: "aurora-azure",
    },
    DatasetBrand {
        slug: "linked-data",
        image_png: include_bytes!("../../docs/assets/dataset-brand/linked-data.png"),
        banner_preset: "aurora-cyan",
    },
    DatasetBrand {
        slug: "capabilities",
        image_png: include_bytes!("../../docs/assets/dataset-brand/capabilities.png"),
        banner_preset: "aurora-rose",
    },
    DatasetBrand {
        slug: "ots-ontology",
        image_png: include_bytes!("../../docs/assets/dataset-brand/ots-ontology.png"),
        banner_preset: "aurora-indigo",
    },
];

/// Entry point — best-effort, never panics out of startup.
pub fn seed_open_triplestore(state: &AppState) {
    let disabled = std::env::var("SEED_STANDARDS_DEMO")
        .map(|v| {
            matches!(
                v.trim().to_ascii_lowercase().as_str(),
                "false" | "0" | "no" | "off"
            )
        })
        .unwrap_or(false);
    if disabled {
        return;
    }
    // Two seeders can run concurrently on a fresh install: the boot task only
    // reaches the demo seed after the SHACL/standards seeding (seconds), and the
    // first-admin registration handler kicks one off the moment that admin
    // exists — the browser-e2e harness registers its admin exactly in that
    // window. The seed is idempotent but not concurrent with itself: both
    // passes see "missing", then race their INSERTs into UNIQUE constraints
    // (and both would download the demo IFC). Serialise process-wide; the
    // second pass then no-ops via the existence checks.
    static SEED_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let _guard = SEED_LOCK.lock().unwrap_or_else(|p| p.into_inner());
    if let Err(e) = try_seed(state) {
        tracing::warn!("open-triplestore demo seed skipped: {e}");
    }
}

/// Build the bundled standards demo as a [`Bundle`] so it runs through the same
/// generic engine ([`seed_bundles::apply_bundle`]) as an on-disk `--seed-dir`
/// bundle — this is the "reference bundle": the one every CI run that exercises
/// the demo seed also exercises the shared seed-bundle code path.
fn build_bundle() -> Bundle {
    let datasets = seed_data::datasets()
        .iter()
        .map(|ds| {
            let graphs = ds
                .graphs
                .iter()
                .map(|g| BundleGraph {
                    iri: format!("{DEMO_BASE}/{}/{}", ds.slug, g.suffix),
                    role: Some(g.role),
                    data: Some((Cow::Borrowed(g.data), g.fmt)),
                })
                .collect();
            BundleDataset {
                slug: ds.slug.to_string(),
                name: ds.name.to_string(),
                description: Some(ds.description.to_string()),
                visibility: Visibility::Public,
                graphs,
                quads: Vec::new(),
                saved_queries: seed_data::services_for(ds.slug),
            }
        })
        .collect();

    Bundle {
        id: "open-triplestore-standards-demo".to_string(),
        // Gating already happens in `seed_open_triplestore` before this bundle
        // is even built; recorded here too so the bundle is self-describing.
        opt_out_env: Some("SEED_STANDARDS_DEMO".to_string()),
        org: OrgSpec {
            slug: ORG_SLUG.to_string(),
            name: ORG_NAME.to_string(),
            description: Some(ORG_DESCRIPTION.to_string()),
        },
        datasets,
    }
}

fn try_seed(state: &AppState) -> anyhow::Result<()> {
    // Snapshot the org's existing branding BEFORE the generic engine runs, so we
    // know whether to seed fresh artwork or only back-fill what's missing on an
    // install seeded before branding shipped.
    let existing_org = state.auth_db.get_organisation_by_slug(ORG_SLUG)?;

    let bundle = build_bundle();
    let report = seed_bundles::apply_bundle(state, &bundle)?;

    match existing_org {
        Some(existing) => seed_org_branding(
            state,
            &report.org_id,
            existing.image_key.is_none(),
            existing.banner_key.is_none(),
        ),
        None => seed_org_branding(state, &report.org_id, true, true),
    }

    // Themed icon + animated banner preset for each dataset THIS run created
    // (never for a pre-existing dataset, so an admin's chosen artwork stands).
    for slug in &report.datasets_created {
        seed_dataset_branding(state, slug, slug, true, true);
    }

    // The Schependomlaan IFC (layered Dutch BIM demo: BOT topology + full ifcOWL
    // lift, every storey/wall/beam individually addressable) loads on first boot
    // so the public demo shows the IFC decomposition immediately. With an admin
    // owner it is also stored as a downloadable asset; without one (brand-new
    // install) the asset is skipped and the FOG file reference points at the
    // source URL — the linked data + decomposition are present either way.
    seed_ifc_buildings(state, report.owner_id.as_deref().unwrap_or(""));

    // Lift the bundled CityJSON sample neighbourhoods (the real 3DBAG block + the
    // authored LoD2 zones) into the store as volumetric WKT-Z, so the 3D-Tiles
    // pipeline (`/3dtiles`) and the 3D R*-tree index have a real cityscape to
    // stream instead of only the handful of authored worked-example solids. Runs
    // after the IFC buildings so its graphs register on the same boot.
    seed_cityjson_volumes(state);

    // Unconditional (unlike `apply_bundle`'s internal marking, which only fires
    // for its own graphs): `seed_cityjson_volumes` loads store data directly
    // without going through a handler that marks the index dirty itself.
    #[cfg(feature = "text-search")]
    state.mark_text_dirty();

    tracing::info!(
        "Seeded/verified '{}' organisation ({}): {} datasets, {} graphs ({} back-filled), {} new services",
        ORG_NAME,
        report.org_id,
        seed_data::datasets().len(),
        report.graphs_registered,
        report.graphs_backfilled,
        report.services_created
    );
    if report.owner_id.is_none() {
        tracing::info!(
            "open-triplestore seed: org + public data created on first load; saved-query \
             services, the IFC demo and org membership are deferred until the first admin registers"
        );
    }
    Ok(())
}

/// Drive `fut` to completion from any calling context. The seed normally runs
/// on a `spawn_blocking` thread, where `Handle::current().block_on` would be
/// fine — but tests call it straight from async workers, where that panics
/// ("Cannot start a runtime from within a runtime"). A throwaway
/// single-thread runtime on a scoped OS thread works from both.
fn block_on_anywhere<T: Send>(
    fut: impl std::future::Future<Output = T> + Send,
) -> anyhow::Result<T> {
    std::thread::scope(|scope| {
        scope
            .spawn(|| {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()?;
                Ok(rt.block_on(fut))
            })
            .join()
            .unwrap_or_else(|panic| std::panic::resume_unwind(panic))
    })
}

/// Default source of the Schependomlaan design-model IFC — the canonical open
/// Dutch BIM dataset (Nijmegen; CC BY 4.0, openBIMstandards/TU Eindhoven),
/// mirrored on GitHub. Override with `SEED_IFC_URL`; disable the whole demo
/// seed with `SEED_STANDARDS_DEMO=false`.
const SCHEPENDOMLAAN_IFC_URL: &str = "https://raw.githubusercontent.com/jakob-beetz/DataSetSchependomlaan/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc";

/// One open IFC building to stand in the unified 3D/BIM demo. Each is downloaded
/// once (first boot), stored as a public asset, and lifted to BOT + ifcOWL in its
/// OWN graph; the WKT anchor overrides the file's IfcSite (exporters leave default
/// locations) so the buildings cluster as a little BIM neighbourhood near the
/// Schependomlaan site in Nijmegen. URLs are CORS-enabled (raw.githubusercontent)
/// so the web-ifc viewer can fetch them client-side too.
struct IfcBuildingSeed {
    /// Stored asset filename.
    name: &'static str,
    /// Open IFC download URL.
    url: &'static str,
    /// `POINT(lon lat)` map anchor (overrides the file's own IfcSite georef).
    anchor: &'static str,
    /// Distinct BOT graph suffix per building so they don't collide.
    graph_suffix: &'static str,
    /// Short label for logs.
    label: &'static str,
}

/// The demo IFC buildings. The small KIT FZK-Haus + buildingSMART Duplex
/// (~2.5 MB each) come FIRST so a couple of rich IFC buildings appear within
/// seconds of first boot; the 49 MB Schependomlaan (which honours `SEED_IFC_URL`)
/// imports last so it doesn't hold the others up. All carry full BOT topology,
/// property sets and an ifcOWL lift.
const IFC_BUILDINGS: &[IfcBuildingSeed] = &[
    IfcBuildingSeed {
        name: "FZK-Haus.ifc",
        url: "https://raw.githubusercontent.com/tum-gis/ifc-to-citygml3/master/input/AC20-FZK-Haus.ifc",
        anchor: "POINT(5.83602 51.84182)",
        graph_suffix: "building-fzk",
        label: "FZK-Haus",
    },
    IfcBuildingSeed {
        name: "Duplex.ifc",
        url: "https://raw.githubusercontent.com/MadsHolten/BOT-Duplex-house/master/Model%20files/IFC/Duplex.ifc",
        anchor: "POINT(5.83180 51.84050)",
        graph_suffix: "building-duplex",
        label: "Duplex Apartment",
    },
    IfcBuildingSeed {
        name: "Schependomlaan.ifc",
        url: SCHEPENDOMLAAN_IFC_URL,
        anchor: "POINT(5.83373 51.84114)",
        graph_suffix: "building",
        label: "Schependomlaan",
    },
];

/// Download each demo IFC building (first boot only) and run it through the same
/// IFC import pipeline users get: stored as a public dataset asset, converted to
/// a BOT topology graph + a full ifcOWL lift, every storey, wall and beam
/// individually addressable. Each building skips instantly when its graph already
/// has data; a failed download just retries on the next boot.
fn seed_ifc_buildings(state: &AppState, owner_id: &str) {
    const DS: &str = "viewer-3d-demo";
    if !matches!(state.auth_db.get_dataset(DS), Ok(Some(_))) {
        return;
    }
    // An explicitly empty SEED_IFC_URL disables the whole IFC demo (also used by
    // tests, which must never reach out to the network). A custom value overrides
    // only the first (Schependomlaan) building.
    let env_url = std::env::var("SEED_IFC_URL").ok();
    if env_url.as_deref().map(str::trim) == Some("") {
        tracing::info!("SEED_IFC_URL is empty — skipping the IFC building demos");
        return;
    }
    for b in IFC_BUILDINGS.iter() {
        let bot_graph = format!("{}/{}/{}", seed_data::DEMO_BASE, DS, b.graph_suffix);
        if state
            .store
            .graph_count_cached(Some(&bot_graph))
            .unwrap_or(0)
            > 0
        {
            continue; // already seeded
        }
        // SEED_IFC_URL overrides only the Schependomlaan source (the headline
        // building), regardless of its position in the list.
        let url = match env_url.as_deref() {
            Some(u) if b.label == "Schependomlaan" && !u.trim().is_empty() => u.to_string(),
            _ => b.url.to_string(),
        };
        tracing::info!(
            "seed: downloading {} IFC ({url}) — first boot only",
            b.label
        );
        let downloaded = block_on_anywhere(async {
            let client = reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(600))
                .build()?;
            let bytes = client
                .get(&url)
                .send()
                .await?
                .error_for_status()?
                .bytes()
                .await?;
            anyhow::Ok(bytes.to_vec())
        })
        .and_then(|r| r);
        let bytes = match downloaded {
            Ok(b2) => b2,
            Err(e) => {
                tracing::warn!(
                    "{} IFC seed skipped (download failed, retries next boot): {e}",
                    b.label
                );
                continue;
            }
        };
        let imported = block_on_anywhere(crate::imports::ifc::import_ifc_bytes(
            state,
            DS,
            owner_id,
            b.name,
            bytes,
            Some(bot_graph),
            true,
            true,
            Some(url),
            Some(b.anchor.to_string()),
        ))
        .and_then(|r| r.map_err(anyhow::Error::msg));
        match imported {
            Ok(o) => tracing::info!(
                "seeded {}: {} elements / {} storeys / {} spaces; BOT {} + ifcOWL {} triples",
                b.label,
                o.stats.elements,
                o.stats.storeys,
                o.stats.spaces,
                o.stats.bot_triples,
                o.stats.ifcowl_triples
            ),
            Err(e) => tracing::warn!("{} IFC seed failed: {e}", b.label),
        }
    }
}

/// One bundled CityJSON neighbourhood lifted to volumetric WKT-Z at seed time.
///
/// The same `.city.json` files the map viewer fetches client-side (`/samples/…`,
/// referenced via OMG/FOG file-links) are also embedded in the binary and parsed
/// to GeoSPARQL `POLYHEDRALSURFACE Z` here, so the 3D-Tiles tileset (which is
/// built purely from store `geo:asWKT`) has the full block to stream. They land
/// in their own `tiles3d-*` graphs, which the viewer-feed/geo-stats routes skip
/// (like `/ifcowl`), so the 2D map keeps rendering its client-side CityJSON and
/// is not doubled up with flattened footprints.
struct CityJsonZoneSeed {
    /// Embedded CityJSON document (one of the bundled samples).
    data: &'static str,
    /// Distinct, feed-excluded graph suffix.
    graph_suffix: &'static str,
    /// PROV `wasDerivedFrom` / attribution for the lifted geometry.
    source: &'static str,
    /// Short label for logs.
    label: &'static str,
}

/// CityJSON neighbourhoods to lift. The real 3DBAG LoD2.2 block is the headline
/// (≈79 building solids); the authored zones add the foreground LoD2 buildings.
const CITYJSON_ZONES: &[CityJsonZoneSeed] = &[
    CityJsonZoneSeed {
        data: include_str!("../../frontend/public/samples/schependomlaan-3dbag.city.json"),
        graph_suffix: "tiles3d-3dbag",
        source: "https://docs.3dbag.nl/en/copyright/",
        label: "3DBAG LoD2.2 block",
    },
    CityJsonZoneSeed {
        data: include_str!("../../frontend/public/samples/neighbourhood.city.json"),
        graph_suffix: "tiles3d-neighbourhood",
        source: "https://creativecommons.org/publicdomain/zero/1.0/",
        label: "authored LoD2 neighbourhood",
    },
    CityJsonZoneSeed {
        data: include_str!("../../frontend/public/samples/schependomlaan-zone2.city.json"),
        graph_suffix: "tiles3d-zone2",
        source: "https://creativecommons.org/publicdomain/zero/1.0/",
        label: "authored LoD2 zone 2",
    },
];

/// Lift the bundled CityJSON neighbourhoods into the demo dataset's store as
/// volumetric WKT-Z (`volumetric_only` — flat LoD0 footprints are dropped), one
/// dedicated `tiles3d-*` graph per sample. Idempotent: each graph is skipped once
/// it holds data, exactly like [`seed_ifc_buildings`]. Best-effort.
fn seed_cityjson_volumes(state: &AppState) {
    use crate::imports::cityjson::{convert_cityjson, CityJsonOptions};
    const DS: &str = "viewer-3d-demo";
    if !matches!(state.auth_db.get_dataset(DS), Ok(Some(_))) {
        return;
    }
    let base = state.base_url.trim_end_matches('/').to_string();
    for z in CITYJSON_ZONES {
        let graph = format!("{}/{}/{}", seed_data::DEMO_BASE, DS, z.graph_suffix);
        if state.store.graph_count_cached(Some(&graph)).unwrap_or(0) > 0 {
            continue; // already seeded
        }
        let opts = CityJsonOptions {
            inst_base: format!("{base}/dataset/{DS}/"),
            source_url: Some(z.source.to_string()),
            generated_at: None,
            // 3D massing only — flat footprints would mesh as redundant ground
            // polygons that z-fight the solids in the tileset.
            volumetric_only: true,
        };
        let doc: serde_json::Value = match serde_json::from_str(z.data) {
            Ok(d) => d,
            Err(e) => {
                tracing::warn!("cityjson volume seed: {} parse failed: {e}", z.label);
                continue;
            }
        };
        let (ntriples, stats) = match convert_cityjson(&doc, &opts) {
            Ok(x) => x,
            Err(e) => {
                tracing::warn!("cityjson volume seed: {} convert failed: {e}", z.label);
                continue;
            }
        };
        if let Err(e) = state.store.graph_store_put(
            Some(graph.as_str()),
            &ntriples,
            oxigraph::io::RdfFormat::NTriples,
        ) {
            tracing::warn!("cityjson volume seed: <{graph}> load failed: {e}");
            continue;
        }
        let _ = state.auth_db.add_dataset_graph(DS, &graph);
        let _ = crate::imports::handlers::detect_and_store_graph_role(state, DS, &graph);
        state.auth_db.invalidate_accessible_graphs_cache();
        tracing::info!(
            "seeded CityJSON volumes ({}): {} objects / {} solids → <{graph}>",
            z.label,
            stats.objects,
            stats.geometries
        );
    }
}

/// Upload the bundled logo/banner for the demo organisation and record their
/// object keys (the same keys the upload endpoints use, so the existing
/// `GET /api/organisations/:id/{image,banner}` handlers serve them). `do_logo`
/// / `do_banner` let the caller back-fill only what's missing. Best-effort:
/// it skips silently when object storage isn't configured and logs (without
/// aborting the seed) on any failure.
fn seed_org_branding(state: &AppState, org_id: &str, do_logo: bool, do_banner: bool) {
    if !state.object_store.is_configured() || (!do_logo && !do_banner) {
        return;
    }
    let assets: [(bool, &str, &'static [u8]); 2] = [
        (do_logo, "org-images", ORG_LOGO_PNG),
        (do_banner, "org-banners", ORG_BANNER_PNG),
    ];
    for (wanted, prefix, bytes) in assets {
        if !wanted {
            continue;
        }
        let key = format!("{prefix}/{org_id}.png");
        let uploaded = block_on_anywhere(state.object_store.upload(
            &key,
            Bytes::from_static(bytes),
            "image/png",
        ))
        .and_then(|r| r);
        if let Err(e) = uploaded {
            tracing::warn!("open-triplestore seed: branding upload to '{key}' failed: {e}");
            continue;
        }
        let recorded = if prefix == "org-images" {
            state.auth_db.update_org_image(org_id, Some(&key))
        } else {
            state.auth_db.update_org_banner(org_id, Some(&key))
        };
        if let Err(e) = recorded {
            tracing::warn!("open-triplestore seed: recording branding key '{key}' failed: {e}");
        }
    }
}

/// Back-fill the themed icon + animated banner preset for one bundled demo
/// dataset (matched by `slug`). `do_image`/`do_banner` let the caller fill only
/// what's currently unset, so it never clobbers artwork an admin has chosen. The
/// banner preset is a DB-only sentinel (`preset:<id>`); the icon upload is
/// skipped silently when object storage isn't configured. Best-effort — failures
/// are logged, never fatal to the seed.
fn seed_dataset_branding(
    state: &AppState,
    dataset_id: &str,
    slug: &str,
    do_image: bool,
    do_banner: bool,
) {
    let Some(brand) = DATASET_BRANDS.iter().find(|b| b.slug == slug) else {
        return;
    };
    if do_banner {
        let key = format!("preset:{}", brand.banner_preset);
        if let Err(e) = state.auth_db.update_dataset_banner(dataset_id, Some(&key)) {
            tracing::warn!("open-triplestore seed: dataset banner preset for '{slug}' failed: {e}");
        }
    }
    if do_image && state.object_store.is_configured() {
        let rt = tokio::runtime::Handle::current();
        let key = format!("dataset-images/{dataset_id}.png");
        match rt.block_on(state.object_store.upload(
            &key,
            Bytes::from_static(brand.image_png),
            "image/png",
        )) {
            Ok(()) => {
                if let Err(e) = state.auth_db.update_dataset_image(dataset_id, Some(&key)) {
                    tracing::warn!(
                        "open-triplestore seed: recording dataset image key '{key}' failed: {e}"
                    );
                }
            }
            Err(e) => {
                tracing::warn!("open-triplestore seed: dataset image upload to '{key}' failed: {e}")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::models::{Role, SystemRole};
    use crate::saved_queries::models::QueryScope;
    use crate::saved_queries::store::SavedQueryStore;
    use crate::server::AppState;
    use crate::store::TripleStore;

    /// Run the demo seed the way production does — on the blocking pool, so the
    /// branding helpers' `Handle::current().block_on` has a runtime to use and the
    /// seeder's internal `block_on`s don't panic on an async worker. An empty
    /// `SEED_IFC_URL` keeps the seeder off the network (no IFC download).
    async fn run_seed(state: &AppState) {
        std::env::set_var("SEED_IFC_URL", "");
        let s = state.clone();
        tokio::task::spawn_blocking(move || seed_open_triplestore(&s))
            .await
            .unwrap();
    }

    /// The org and all its PUBLIC data are created on first boot, before anyone
    /// has registered — the headline fix. Owner-attributed content (membership +
    /// saved-query services) is deferred until an admin exists.
    #[tokio::test]
    async fn creates_org_and_public_data_on_first_load_without_any_user() {
        let state = AppState::test_default_with_store(TripleStore::in_memory().unwrap());
        assert_eq!(state.auth_db.count_users().unwrap(), 0, "fresh install");

        run_seed(&state).await;

        let org = state
            .auth_db
            .get_organisation_by_slug(ORG_SLUG)
            .unwrap()
            .expect("org is created on first load, not first login");
        assert_eq!(org.name, ORG_NAME);

        // Every public demo dataset exists already.
        for ds in seed_data::datasets() {
            assert!(
                matches!(state.auth_db.get_dataset(ds.slug), Ok(Some(_))),
                "dataset '{}' created on first load",
                ds.slug
            );
        }

        // Owner-attributed content is deferred: no members, no services yet.
        assert!(
            state.auth_db.list_org_members(&org.id).unwrap().is_empty(),
            "org has no members until the first admin registers"
        );
        let sq = SavedQueryStore::new(state.auth_db.pool());
        for ds in seed_data::datasets() {
            assert!(
                sq.list(QueryScope::Dataset, ds.slug)
                    .unwrap_or_default()
                    .is_empty(),
                "saved-query services deferred for '{}'",
                ds.slug
            );
        }
    }

    /// Once the first admin exists, the (idempotent) reseed back-fills the
    /// owner-attributed content the first-load seed deferred.
    #[tokio::test]
    async fn backfills_membership_and_services_once_an_admin_exists() {
        let state = AppState::test_default_with_store(TripleStore::in_memory().unwrap());

        // First boot, no users: org + public data, services deferred.
        run_seed(&state).await;
        let demo_ds = seed_data::datasets()[0].slug;
        let sq = SavedQueryStore::new(state.auth_db.pool());
        assert!(
            sq.list(QueryScope::Dataset, demo_ds)
                .unwrap_or_default()
                .is_empty(),
            "no services before an admin exists"
        );

        // The first admin appears (promoted to super_admin in the real flow).
        let admin = state
            .auth_db
            .create_user(
                "admin-1",
                "admin",
                "admin@x.test",
                "hash",
                SystemRole::SuperAdmin,
            )
            .unwrap();

        // Reseed, exactly as the registration handler does on first admin.
        run_seed(&state).await;

        let org = state
            .auth_db
            .get_organisation_by_slug(ORG_SLUG)
            .unwrap()
            .unwrap();
        let members = state.auth_db.list_org_members(&org.id).unwrap();
        assert!(
            members
                .iter()
                .any(|(u, r)| u.id == admin.id && matches!(r, Role::Admin)),
            "first admin back-filled as an Admin member of the org"
        );
        assert!(
            !sq.list(QueryScope::Dataset, demo_ds)
                .unwrap_or_default()
                .is_empty(),
            "saved-query services back-filled once an owner exists"
        );
    }
}
