//! Vocabulary catalog — LOV metadata snapshot + platform registry overlay.
//!
//! The embedded catalog (`assets/vocab/lov-catalog.json.gz`, generated by
//! `scripts/build_lov_catalog.py`) describes every vocabulary in the Linked
//! Open Vocabularies corpus: prefix, namespace, titles, descriptions, tags,
//! version history and reuse metrics.  At runtime the catalog is overlaid
//! with the **public** entries of this instance's model/vocabulary registry,
//! so platform vocabularies rank first and LOV vocabularies whose namespace
//! is already registered are marked `installed`.
//!
//! The overlay keeps every registry entry, tagged with its visibility;
//! catalog reads take a caller predicate so anonymous users see only public
//! entries while owners also find their own private vocabularies.  Shared,
//! caller-independent surfaces (the prefix overlay and the term index) stay
//! strictly public-only so private entries never leak into anonymous
//! rankings.
//!
//! The catalog itself is independent of the `vocab-search` Cargo feature —
//! vocabulary-level search works on every build; only term-level search
//! needs the Tantivy engine.

use std::collections::HashMap;
use std::io::Read;
use std::sync::RwLock;

use serde::{Deserialize, Serialize};

use crate::data_models::models::DataModelRecord;
use crate::kind_detector::RegistryKind;

// ─── Embedded LOV catalog ────────────────────────────────────────────────────

const CATALOG_GZ: &[u8] = include_bytes!("../../assets/vocab/lov-catalog.json.gz");

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LangString {
    pub value: String,
    #[serde(default)]
    pub lang: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct VocabMetrics {
    #[serde(default)]
    pub occurrences_in_datasets: u64,
    #[serde(default)]
    pub reused_by_datasets: u64,
    #[serde(default)]
    pub reused_by_vocabularies: u64,
    #[serde(default)]
    pub incoming_links: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VocabVersionInfo {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub issued: Option<String>,
    #[serde(default)]
    pub class_count: u64,
    #[serde(default)]
    pub property_count: u64,
    #[serde(default)]
    pub datatype_count: u64,
    #[serde(default)]
    pub instance_count: u64,
}

/// One LOV vocabulary record, as embedded.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LovVocab {
    pub prefix: String,
    pub uri: String,
    pub nsp: String,
    #[serde(default)]
    pub titles: Vec<LangString>,
    #[serde(default)]
    pub descriptions: Vec<LangString>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub homepage: Option<String>,
    #[serde(default)]
    pub is_defined_by: Option<String>,
    #[serde(default)]
    pub issued: Option<String>,
    #[serde(default)]
    pub modified: Option<String>,
    #[serde(default)]
    pub langs: Vec<String>,
    #[serde(default)]
    pub creators: Vec<String>,
    #[serde(default)]
    pub contributors: Vec<String>,
    #[serde(default)]
    pub publishers: Vec<String>,
    #[serde(default)]
    pub metrics: VocabMetrics,
    #[serde(default)]
    pub versions: Vec<VocabVersionInfo>,
    /// Quads of this vocabulary's graph in the LOV corpus (0 = not present,
    /// i.e. not installable from the bundled corpus).
    #[serde(default)]
    pub graph_quads: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatalogSource {
    pub url: String,
    pub snapshot_date: String,
    pub sha256: String,
    pub license: String,
    pub attribution: String,
}

#[derive(Deserialize)]
struct CatalogFile {
    format_version: u32,
    source: CatalogSource,
    vocabularies: Vec<LovVocab>,
    #[serde(default)]
    term_metrics: HashMap<String, [u64; 2]>,
}

// ─── Platform overlay ────────────────────────────────────────────────────────

/// A registry entry projected into the catalog (any visibility; reads
/// filter through a caller predicate).
#[derive(Debug, Clone, Serialize)]
pub struct PlatformVocab {
    /// Registry id — also used as the prefix label where valid.
    pub id: String,
    pub title: String,
    pub namespace: String,
    #[serde(default)]
    pub description: Option<String>,
    pub kind: String,
    pub latest_published: Option<String>,
    pub version_count: usize,
    #[serde(skip)]
    pub is_public: bool,
    #[serde(skip)]
    pub owner_type: Option<String>,
    #[serde(skip)]
    pub owner_id: Option<String>,
}

/// Caller-visibility predicate over platform entries.
pub type ViewerPredicate<'a> = &'a dyn Fn(&PlatformVocab) -> bool;

/// The anonymous viewer: public entries only.
pub fn public_only(v: &PlatformVocab) -> bool {
    v.is_public
}

#[derive(Default)]
struct PlatformOverlay {
    vocabs: Vec<PlatformVocab>,
    /// Exact namespace → index into `vocabs`.
    by_nsp_exact: HashMap<String, usize>,
    /// Canonicalized namespace → index (scheme/trailing-char-insensitive
    /// fallback; exact wins so canonical collisions can't shadow a vocab).
    by_nsp_canon: HashMap<String, usize>,
    by_id: HashMap<String, usize>,
}

impl PlatformOverlay {
    fn lookup_nsp(&self, nsp: &str) -> Option<usize> {
        self.by_nsp_exact
            .get(nsp)
            .or_else(|| self.by_nsp_canon.get(&canon_nsp(nsp)))
            .copied()
    }
}

/// Strip a trailing `#` or `/` so `http://schema.org/` and
/// `https://schema.org` compare equal enough for installed-detection.
fn canon_nsp(nsp: &str) -> String {
    let n = nsp.trim_end_matches(['#', '/']);
    n.strip_prefix("https://")
        .or_else(|| n.strip_prefix("http://"))
        .unwrap_or(n)
        .to_string()
}

// ─── Combined catalog ────────────────────────────────────────────────────────

/// A catalog entry as served by the API: either a platform vocabulary or a
/// LOV vocabulary (possibly installed on the platform).
#[derive(Debug, Clone, Serialize)]
pub struct CatalogEntry {
    pub prefix: String,
    pub uri: String,
    pub nsp: String,
    pub titles: Vec<LangString>,
    pub descriptions: Vec<LangString>,
    pub tags: Vec<String>,
    pub homepage: Option<String>,
    pub issued: Option<String>,
    pub langs: Vec<String>,
    pub creators: Vec<String>,
    pub metrics: VocabMetrics,
    pub versions: Vec<VocabVersionInfo>,
    /// `platform` (registered here) or `lov` (catalog-only).
    pub source: &'static str,
    /// Set when the vocabulary is registered on this instance.
    pub model_id: Option<String>,
    /// True when the bundled corpus contains this vocabulary's triples, so
    /// an admin can install it without any network access.
    pub installable: bool,
}

pub struct VocabCatalog {
    source: CatalogSource,
    lov: Vec<LovVocab>,
    by_prefix: HashMap<String, usize>,
    by_uri: HashMap<String, usize>,
    by_nsp_exact: HashMap<String, usize>,
    by_nsp_canon: HashMap<String, usize>,
    term_metrics: HashMap<String, [u64; 2]>,
    platform: RwLock<PlatformOverlay>,
}

impl VocabCatalog {
    /// Decode the embedded catalog. Panics only on a corrupt embedded asset
    /// (covered by `cargo test`).
    pub fn bundled() -> Self {
        let mut json = Vec::new();
        flate2::read::GzDecoder::new(CATALOG_GZ)
            .read_to_end(&mut json)
            .expect("embedded lov-catalog.json.gz decodes");
        let file: CatalogFile =
            serde_json::from_slice(&json).expect("embedded lov-catalog.json.gz parses");
        assert_eq!(file.format_version, 1, "unsupported catalog format");

        let mut by_prefix = HashMap::new();
        let mut by_uri = HashMap::new();
        let mut by_nsp_exact = HashMap::new();
        let mut by_nsp_canon = HashMap::new();
        for (i, v) in file.vocabularies.iter().enumerate() {
            by_prefix.entry(v.prefix.clone()).or_insert(i);
            by_uri.entry(v.uri.clone()).or_insert(i);
            by_nsp_exact.entry(v.nsp.clone()).or_insert(i);
            by_nsp_canon.entry(canon_nsp(&v.nsp)).or_insert(i);
        }
        Self {
            source: file.source,
            lov: file.vocabularies,
            by_prefix,
            by_uri,
            by_nsp_exact,
            by_nsp_canon,
            term_metrics: file.term_metrics,
            platform: RwLock::new(PlatformOverlay::default()),
        }
    }

    pub fn source(&self) -> &CatalogSource {
        &self.source
    }

    pub fn lov_len(&self) -> usize {
        self.lov.len()
    }

    /// LOD-corpus reuse metrics for a term IRI: `[occurrences, datasets]`.
    pub fn term_metrics(&self, iri: &str) -> Option<[u64; 2]> {
        self.term_metrics.get(iri).copied()
    }

    /// Raw LOV record by prefix (used by the corpus indexer / installer).
    pub fn lov_by_prefix(&self, prefix: &str) -> Option<&LovVocab> {
        self.by_prefix.get(prefix).map(|&i| &self.lov[i])
    }

    /// Raw LOV record whose graph in the corpus is `graph_uri`.
    pub fn lov_by_uri(&self, uri: &str) -> Option<&LovVocab> {
        self.by_uri.get(uri).map(|&i| &self.lov[i])
    }

    /// Replace the platform overlay with the registry entries (all
    /// visibilities; reads filter per caller).  Public entries win namespace
    /// collisions so a private duplicate can never shadow a public one.
    pub fn set_platform_records(&self, records: &[DataModelRecord]) {
        let mut overlay = PlatformOverlay::default();
        let mut ordered: Vec<&DataModelRecord> =
            records.iter().filter(|r| !r.namespace.is_empty()).collect();
        ordered.sort_by_key(|r| !r.is_public);
        for r in ordered {
            let idx = overlay.vocabs.len();
            overlay
                .by_nsp_exact
                .entry(r.namespace.clone())
                .or_insert(idx);
            overlay
                .by_nsp_canon
                .entry(canon_nsp(&r.namespace))
                .or_insert(idx);
            overlay.by_id.entry(r.id.clone()).or_insert(idx);
            overlay.vocabs.push(PlatformVocab {
                id: r.id.clone(),
                title: r.title.clone(),
                namespace: r.namespace.clone(),
                description: r.description.clone(),
                kind: match r.kind {
                    RegistryKind::Vocabulary => "vocabulary".to_string(),
                    _ => "data-model".to_string(),
                },
                latest_published: r.latest_published.clone(),
                version_count: r.version_count,
                is_public: r.is_public,
                owner_type: r.owner_type.clone(),
                owner_id: r.owner_id.clone(),
            });
        }
        let mut guard = self.platform.write().unwrap_or_else(|e| e.into_inner());
        *guard = overlay;
    }

    /// Prefix pairs (label → namespace) for seeding the prefix registry's
    /// platform overlay: **public** entries only — the prefix overlay feeds
    /// anonymous, caller-independent surfaces.
    pub fn platform_prefix_pairs(&self) -> Vec<(String, String)> {
        let overlay = self.platform.read().unwrap_or_else(|e| e.into_inner());
        overlay
            .vocabs
            .iter()
            .filter(|v| v.is_public)
            .map(|v| (v.id.clone(), v.namespace.clone()))
            .collect()
    }

    fn entry_from_lov(&self, v: &LovVocab, overlay: &PlatformOverlay) -> CatalogEntry {
        let model_id = overlay
            .lookup_nsp(&v.nsp)
            .map(|i| overlay.vocabs[i].id.clone());
        CatalogEntry {
            prefix: v.prefix.clone(),
            uri: v.uri.clone(),
            nsp: v.nsp.clone(),
            titles: v.titles.clone(),
            descriptions: v.descriptions.clone(),
            tags: v.tags.clone(),
            homepage: v.homepage.clone(),
            issued: v.issued.clone(),
            langs: v.langs.clone(),
            creators: v.creators.clone(),
            metrics: v.metrics.clone(),
            versions: v.versions.clone(),
            source: "lov",
            model_id,
            installable: v.graph_quads > 0,
        }
    }

    fn entry_from_platform(&self, v: &PlatformVocab) -> CatalogEntry {
        // Enrich platform entries with LOV metadata when the namespace matches.
        let lov = self
            .by_nsp_exact
            .get(&v.namespace)
            .or_else(|| self.by_nsp_canon.get(&canon_nsp(&v.namespace)))
            .map(|&i| &self.lov[i]);
        CatalogEntry {
            prefix: v.id.clone(),
            uri: lov
                .map(|l| l.uri.clone())
                .unwrap_or_else(|| v.namespace.clone()),
            nsp: v.namespace.clone(),
            titles: vec![LangString {
                value: v.title.clone(),
                lang: None,
            }],
            descriptions: v
                .description
                .clone()
                .map(|d| {
                    vec![LangString {
                        value: d,
                        lang: None,
                    }]
                })
                .unwrap_or_default(),
            tags: lov.map(|l| l.tags.clone()).unwrap_or_default(),
            homepage: lov.and_then(|l| l.homepage.clone()),
            issued: lov.and_then(|l| l.issued.clone()),
            langs: lov.map(|l| l.langs.clone()).unwrap_or_default(),
            creators: lov.map(|l| l.creators.clone()).unwrap_or_default(),
            metrics: lov.map(|l| l.metrics.clone()).unwrap_or_default(),
            versions: lov.map(|l| l.versions.clone()).unwrap_or_default(),
            source: "platform",
            model_id: Some(v.id.clone()),
            installable: false,
        }
    }

    /// All entries visible to the caller: platform vocabularies first, then
    /// LOV-only ones.
    pub fn list(&self, can_see: ViewerPredicate) -> Vec<CatalogEntry> {
        let overlay = self.platform.read().unwrap_or_else(|e| e.into_inner());
        let mut out: Vec<CatalogEntry> = overlay
            .vocabs
            .iter()
            .filter(|v| can_see(v))
            .map(|v| self.entry_from_platform(v))
            .collect();
        for v in &self.lov {
            let registered = overlay
                .lookup_nsp(&v.nsp)
                .is_some_and(|i| can_see(&overlay.vocabs[i]));
            if !registered {
                out.push(self.entry_from_lov(v, &overlay));
            }
        }
        out
    }

    /// Lookup by prefix, ontology URI or namespace (LOV `vocabulary/info`
    /// semantics: `$or` over the three, with `#`/`/` canonicalization).
    pub fn info(&self, key: &str, can_see: ViewerPredicate) -> Option<CatalogEntry> {
        let overlay = self.platform.read().unwrap_or_else(|e| e.into_inner());
        if let Some(&i) = overlay.by_id.get(key) {
            if can_see(&overlay.vocabs[i]) {
                return Some(self.entry_from_platform(&overlay.vocabs[i]));
            }
        }
        if let Some(i) = overlay.lookup_nsp(key) {
            if can_see(&overlay.vocabs[i]) {
                return Some(self.entry_from_platform(&overlay.vocabs[i]));
            }
        }
        let idx = self
            .by_prefix
            .get(key)
            .or_else(|| self.by_uri.get(key))
            .or_else(|| self.by_nsp_exact.get(key))
            .or_else(|| self.by_nsp_canon.get(&canon_nsp(key)));
        idx.map(|&i| self.entry_from_lov(&self.lov[i], &overlay))
    }

    /// All tags with usage counts, descending.
    pub fn tags(&self) -> Vec<(String, usize)> {
        let mut counts: HashMap<&str, usize> = HashMap::new();
        for v in &self.lov {
            for t in &v.tags {
                *counts.entry(t.as_str()).or_default() += 1;
            }
        }
        let mut out: Vec<(String, usize)> = counts
            .into_iter()
            .map(|(t, c)| (t.to_string(), c))
            .collect();
        out.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
        out
    }

    /// Ranked vocabulary search (LOV `vocabulary/search` semantics: prefix
    /// matches dominate, then titles, then descriptions/tags; without a
    /// query, alphabetical by prefix with platform entries first).
    pub fn search(
        &self,
        query: &str,
        tag_filters: &[String],
        lang_filters: &[String],
        limit: usize,
        offset: usize,
        can_see: ViewerPredicate,
    ) -> (usize, Vec<CatalogEntry>) {
        let q = query.trim().to_ascii_lowercase();
        let mut matches: Vec<(f64, CatalogEntry)> = Vec::new();
        for entry in self.list(can_see) {
            if !tag_filters.is_empty()
                && !tag_filters
                    .iter()
                    .all(|t| entry.tags.iter().any(|et| et.eq_ignore_ascii_case(t)))
            {
                continue;
            }
            if !lang_filters.is_empty()
                && !lang_filters
                    .iter()
                    .any(|l| entry.langs.iter().any(|el| el.eq_ignore_ascii_case(l)))
            {
                continue;
            }
            let score = if q.is_empty() {
                0.0
            } else {
                let mut s = 0.0f64;
                let prefix = entry.prefix.to_ascii_lowercase();
                // Mirrors LOV's prefix.autocomplete^12 / title^3 / description^1.5.
                if prefix == q {
                    s += 120.0;
                } else if prefix.starts_with(&q) {
                    s += 60.0;
                } else if prefix.contains(&q) {
                    s += 30.0;
                }
                for t in &entry.titles {
                    let tv = t.value.to_ascii_lowercase();
                    if tv == q {
                        s += 40.0;
                    } else if tv.contains(&q) {
                        s += 20.0;
                    }
                }
                for d in &entry.descriptions {
                    if d.value.to_ascii_lowercase().contains(&q) {
                        s += 8.0;
                        break;
                    }
                }
                if entry
                    .tags
                    .iter()
                    .any(|t| t.to_ascii_lowercase().contains(&q))
                {
                    s += 10.0;
                }
                if entry.nsp.to_ascii_lowercase().contains(&q) {
                    s += 6.0;
                }
                if s == 0.0 {
                    continue;
                }
                // Popularity tie-break, dampened.
                s + (1.0 + entry.metrics.incoming_links as f64).ln()
            };
            matches.push((score, entry));
        }
        if q.is_empty() {
            matches.sort_by(|a, b| {
                let plat = |e: &CatalogEntry| e.source != "platform";
                plat(&a.1)
                    .cmp(&plat(&b.1))
                    .then_with(|| a.1.prefix.cmp(&b.1.prefix))
            });
        } else {
            matches.sort_by(|a, b| {
                b.0.partial_cmp(&a.0)
                    .unwrap_or(std::cmp::Ordering::Equal)
                    .then_with(|| a.1.prefix.cmp(&b.1.prefix))
            });
        }
        let total = matches.len();
        let page = matches
            .into_iter()
            .skip(offset)
            .take(limit)
            .map(|(_, e)| e)
            .collect();
        (total, page)
    }

    /// Prefix-typeahead over vocabulary prefixes and title words.
    pub fn autocomplete(
        &self,
        query: &str,
        limit: usize,
        can_see: ViewerPredicate,
    ) -> Vec<CatalogEntry> {
        let q = query.trim().to_ascii_lowercase();
        if q.is_empty() {
            return Vec::new();
        }
        let mut hits: Vec<(i64, CatalogEntry)> = Vec::new();
        for entry in self.list(can_see) {
            let prefix = entry.prefix.to_ascii_lowercase();
            let score = if prefix == q {
                3
            } else if prefix.starts_with(&q) {
                2
            } else if entry
                .titles
                .iter()
                .any(|t| t.value.to_ascii_lowercase().starts_with(&q))
            {
                1
            } else {
                continue;
            };
            hits.push((score, entry));
        }
        hits.sort_by(|a, b| {
            b.0.cmp(&a.0)
                .then_with(|| b.1.metrics.incoming_links.cmp(&a.1.metrics.incoming_links))
                .then_with(|| a.1.prefix.cmp(&b.1.prefix))
        });
        hits.into_iter().take(limit).map(|(_, e)| e).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_loads() {
        let cat = VocabCatalog::bundled();
        assert!(
            cat.lov_len() > 800,
            "expected >800 vocabs, got {}",
            cat.lov_len()
        );
        assert_eq!(cat.source().license, "CC BY 4.0");
    }

    #[test]
    fn info_resolves_prefix_uri_and_namespace() {
        let cat = VocabCatalog::bundled();
        let by_prefix = cat.info("foaf", &public_only).expect("foaf by prefix");
        assert_eq!(by_prefix.nsp, "http://xmlns.com/foaf/0.1/");
        let by_nsp = cat
            .info("http://xmlns.com/foaf/0.1/", &public_only)
            .expect("foaf by nsp");
        assert_eq!(by_nsp.prefix, "foaf");
        assert!(cat.info("definitely-not-a-vocab", &public_only).is_none());
    }

    #[test]
    fn search_ranks_prefix_match_first() {
        let cat = VocabCatalog::bundled();
        let (total, hits) = cat.search("foaf", &[], &[], 10, 0, &public_only);
        assert!(total >= 1);
        assert_eq!(hits[0].prefix, "foaf");
    }

    #[test]
    fn search_supports_tag_filter() {
        let cat = VocabCatalog::bundled();
        let (_, hits) = cat.search("", &["Geography".to_string()], &[], 20, 0, &public_only);
        assert!(!hits.is_empty());
        assert!(hits
            .iter()
            .all(|h| h.tags.iter().any(|t| t.eq_ignore_ascii_case("Geography"))));
    }

    #[test]
    fn platform_overlay_marks_installed() {
        let cat = VocabCatalog::bundled();
        cat.set_platform_records(&[DataModelRecord {
            id: "foaf".into(),
            title: "FOAF".into(),
            namespace: "http://xmlns.com/foaf/0.1/".into(),
            description: None,
            is_public: true,
            owner_type: None,
            owner_id: None,
            latest_published: Some("0.99".into()),
            latest_draft: None,
            version_count: 1,
            created_at: String::new(),
            created_by: None,
            kind: RegistryKind::Vocabulary,
        }]);
        let info = cat.info("foaf", &public_only).expect("foaf");
        assert_eq!(info.source, "platform");
        assert_eq!(info.model_id.as_deref(), Some("foaf"));
        // LOV enrichment carried over (tags/metrics from the catalog).
        assert!(info.metrics.incoming_links > 0);

        // Private records must not appear.
        cat.set_platform_records(&[DataModelRecord {
            id: "secret".into(),
            title: "Secret".into(),
            namespace: "https://example.org/secret#".into(),
            description: None,
            is_public: false,
            owner_type: Some("user".into()),
            owner_id: Some("u1".into()),
            latest_published: None,
            latest_draft: None,
            version_count: 1,
            created_at: String::new(),
            created_by: None,
            kind: RegistryKind::Vocabulary,
        }]);
        // Anonymous viewers can't see it…
        assert!(cat.info("secret", &public_only).is_none());
        // …but a predicate representing the owner can.
        let owner_view = |_v: &PlatformVocab| true;
        let secret = cat
            .info("secret", &owner_view)
            .expect("owner sees own entry");
        assert_eq!(secret.source, "platform");
    }

    #[test]
    fn term_metrics_present() {
        let cat = VocabCatalog::bundled();
        // The dump carries LOD-corpus metrics for a couple thousand popular terms.
        assert!(cat
            .term_metrics("http://www.geonames.org/ontology#Feature")
            .is_some());
    }
}
